Jenkinsfile.cicd

Initial CI/CD

---

prime-angular-frontend/src/app/app-config.module.ts
prime-angular-frontend/src/app/auth/shared/components/auth/auth.component.html
prime-angular-frontend/src/app/config/config-code.pipe.spec.ts
prime-angular-frontend/src/app/config/config-code.pipe.ts
prime-angular-frontend/src/app/config/config.module.ts
prime-angular-frontend/src/app/core/components/maintenance/maintenance.component.html
prime-angular-frontend/src/app/core/components/maintenance/maintenance.component.spec.ts
prime-angular-frontend/src/app/core/components/maintenance/maintenance.component.ts
prime-angular-frontend/src/app/core/core.module.ts
prime-angular-frontend/src/app/features/enrolment/enrolment-routing.module.ts
prime-angular-frontend/src/app/features/enrolment/enrolment.module.ts
prime-angular-frontend/src/app/features/enrolment/pages/confirmation/confirmation.component.html
prime-angular-frontend/src/app/features/enrolment/pages/confirmation/confirmation.component.scss
prime-angular-frontend/src/app/features/enrolment/pages/confirmation/confirmation.component.spec.ts
prime-angular-frontend/src/app/features/enrolment/pages/confirmation/confirmation.component.ts
prime-angular-frontend/src/app/features/enrolment/pages/pharmanet-access/pharmanet-access.component.html
prime-angular-frontend/src/app/features/enrolment/pages/profile/profile.component.ts
prime-angular-frontend/src/app/features/enrolment/pages/review/review.component.html
prime-angular-frontend/src/app/features/enrolment/pages/review/review.component.ts
prime-angular-frontend/src/app/features/enrolment/shared/components/dashboard/dashboard.component.html
prime-angular-frontend/src/app/features/enrolment/shared/components/dashboard/dashboard.component.ts
prime-angular-frontend/src/app/features/enrolment/shared/components/page-title/page-title.component.ts
prime-angular-frontend/src/app/features/enrolment/shared/components/sub-header/sub-header.component.html
prime-angular-frontend/src/app/shared/components/header/header.component.html
prime-angular-frontend/src/app/shared/components/header/header.component.scss
prime-angular-frontend/src/app/shared/components/header/header.component.ts
prime-angular-frontend/src/app/shared/shared.module.ts

Added temporary confirmation page
Added mobile side menu icon
Added config pipes
General updates to the UI

PRIME-93 - UI Updates

---

prime-angular-frontend/src/app/modules/enrolment/pages/professional-info/professional-info.component.html
prime-angular-frontend/src/app/modules/enrolment/pages/professional-info/professional-info.component.ts
prime-angular-frontend/src/app/modules/enrolment/pages/review/review.component.html
prime-angular-frontend/src/app/modules/enrolment/shared/components/college-certifications/college-certifications.component.html
prime-angular-frontend/src/app/modules/enrolment/shared/components/college-certifications/college-certifications.component.ts

* Updated enrolment review field visibility
* Updated professional information to display an initial certification when selected

Enrolment Updates

---

prime-angular-frontend/src/app/shared/components/dashboard/dashboard.component.ts

Proper logout

---

prime-angular-frontend/src/app/modules/enrolment/pages/review/review.component.html
prime-angular-frontend/src/app/modules/enrolment/pages/summary/summary.component.html
prime-angular-frontend/src/app/modules/enrolment/shared/models/enrollee.model.ts
prime-angular-frontend/src/app/modules/enrolment/shared/models/enrollee.spec.ts
prime-angular-frontend/src/app/shared/models/enrolment.model.ts
prime-angular-frontend/src/app/shared/pipes/enrolment.pipe.spec.ts
prime-angular-frontend/src/app/shared/pipes/enrolment.pipe.ts
prime-angular-frontend/src/app/shared/shared.module.ts

Add enrolment pipe to review page, summary page
Create enrollee class, add to Enrolment interface

enrolment pipe

---

prime-angular-frontend/src/app/shared/pipes/phone.pipe.ts

The phone pipe is throwing errors if null is passed in (user hasn't filled out profile).
Added simple guard.

Fix for phone pipe

---

openshift/json/postgresql.dc.json
player.sh

Suffix not required
Cleanup PVC

Fixing template, cleanup

---

openshift/dotnet-webapi.bc.yaml
openshift/dotnet-webapi.dc.yaml
openshift/postgresql.dc.yaml

JWT_ADMIN_CLIENT = prime-admin-local > prime-admin-[dev|test|prod]
JWT_USER_CLIENT = prime-application-local > prime-application-[dev|test|prod]
JWT_AUDIENCE = prime-web-api 
JWT_WELL_KNOWN_CONFIG = https://sso-[dev|test|prod].pathfinder.gov.bc.ca/auth/realms/v4mbqqas/.well-known/openid-configuration

We need tokens for JWT values for keycloak

---

prime-angular-frontend/src/app/config/config.service.ts

* Added config interface
* Added getter return types, and 
* Removed hardcoded countries and provinces

Config Service Updates

---

prime-angular-frontend/src/app/modules/enrolment/pages/pharmanet-access/pharmanet-access.component.spec.ts
prime-angular-frontend/src/app/modules/enrolment/pages/professional-info/professional-info.component.spec.ts
prime-angular-frontend/src/app/modules/enrolment/pages/profile/profile.component.spec.ts

* Updated test dependency provider for mock config service

Dependency Provider

---

prime-angular-frontend/src/app/app-routing.module.ts
prime-angular-frontend/src/app/core/guards/base.guard.ts
prime-angular-frontend/src/app/modules/auth/shared/guards/authentication.guard.ts
prime-angular-frontend/src/app/modules/auth/shared/guards/authorization-redirect.guard.ts
prime-angular-frontend/src/app/modules/enrolment/enrolment-routing.module.ts
prime-angular-frontend/src/app/modules/enrolment/shared/guards/enrollee.guard.ts
prime-angular-frontend/src/app/modules/enrolment/shared/guards/enrolment.guard.ts
prime-angular-frontend/src/app/modules/provision/provision-routing.module.ts
prime-angular-frontend/src/app/modules/provision/shared/guards/provision.guard.ts

* Restored and refactored guards to use updates to AuthService

Route Guards

---

documentation/Keycloak settings/realm-export-dev.json

Keycloak settings were deleted by accident, re-adding them to the project

Re-add old keycloak settings

---

documentation/Keycloak settings/realm-export-dev.json
documentation/Keycloak settings/realm-export-test.json

Up-to-date Keycloak configurations for dev and test

Update Keycloak configs

---

prime-angular-frontend/src/app/shared/components/dashboard/dashboard.component.html
prime-angular-frontend/src/app/shared/components/dashboard/dashboard.component.ts
prime-angular-frontend/src/app/shared/components/header/header.component.html
prime-angular-frontend/src/app/shared/components/header/header.component.scss
prime-angular-frontend/src/app/shared/components/header/header.component.ts

* Updated application header to include username and logout

Application Header

---

prime-angular-frontend/src/app/shared/modules/ngx-material/ngx-material.module.ts
prime-angular-frontend/src/app/shared/pipes/format-date.pipe.ts

* Updated date format for DatePicker
* Updated date format for FormatDatePipe

Date Format

---

prime-angular-frontend/src/app/modules/enrolment/pages/self-declaration/self-declaration.component.html
prime-angular-frontend/src/app/modules/enrolment/pages/self-declaration/self-declaration.component.ts
prime-angular-frontend/src/app/modules/enrolment/shared/services/enrolment-state.service.ts

* Error validation alert at top
* Start with nothing selected
* Don't show character limit in details,

Self Declaration

---

prime-angular-frontend/src/app/modules/adjudication/pages/enrolments/enrolments.component.ts
prime-angular-frontend/src/app/modules/enrolment/pages/collection-notice/collection-notice.component.spec.ts
prime-angular-frontend/src/app/modules/enrolment/pages/regulatory/regulatory.component.spec.ts
prime-angular-frontend/src/app/modules/enrolment/shared/components/college-certification-form/college-certification-form.component.html
prime-angular-frontend/src/app/modules/enrolment/shared/components/college-certification-form/college-certification-form.component.spec.ts
prime-angular-frontend/src/app/shared/modules/ngx-material/ngx-material.module.ts
prime-angular-frontend/src/app/shared/pipes/enrolment.pipe.ts
prime-angular-frontend/src/app/shared/shared.module.ts

* Changed label position
* Fixed testing and linting errors

Form Update

---

prime-angular-frontend/.vscode/extensions.json
prime-angular-frontend/src/app/config/config.model.ts
prime-angular-frontend/src/app/core/interceptors/error-handler.interceptor.ts
prime-angular-frontend/src/app/modules/adjudication/pages/enrolments/enrolments.component.ts
prime-angular-frontend/src/app/modules/auth/pages/info/info.component.scss
prime-angular-frontend/src/app/modules/enrolment/pages/job/job.component.html
prime-angular-frontend/src/app/modules/enrolment/pages/job/job.component.ts
prime-angular-frontend/src/app/modules/enrolment/pages/organization/organization.component.html
prime-angular-frontend/src/app/modules/enrolment/pages/organization/organization.component.ts
prime-angular-frontend/src/app/modules/enrolment/pages/profile/profile.component.html
prime-angular-frontend/src/app/modules/enrolment/pages/regulatory/regulatory.component.ts
prime-angular-frontend/src/app/modules/enrolment/pages/self-declaration/self-declaration.component.html
prime-angular-frontend/src/app/modules/enrolment/shared/components/job-form/job-form.component.html
prime-angular-frontend/src/app/modules/enrolment/shared/components/job-form/job-form.component.ts
prime-angular-frontend/src/app/modules/enrolment/shared/services/enrolment-resource.service.ts
prime-angular-frontend/src/app/modules/enrolment/shared/services/enrolment-state.service.ts

* Updated enrolment jobs
* Filter on available jobs based on all selected jobs
* Make an individual job immutable
* Filter auto-complete on individual jobs
* Allow/prevent job default option
* Make jobs required with addition of default option
* Prevent submission of incomplete jobs
* Minor updates to certifications and organizations

Form Updates

---

prime-angular-frontend/src/app/shared/components/form-icon-group/form-icon-group.component.html
prime-angular-frontend/src/app/shared/components/form-icon-group/form-icon-group.component.scss
prime-angular-frontend/src/app/shared/components/form-icon-group/form-icon-group.component.ts
prime-angular-frontend/src/app/shared/modules/ngx-contextual-help/contextual-help/contextual-help.component.html
prime-angular-frontend/src/app/shared/modules/ngx-contextual-help/contextual-help/contextual-help.component.ts

* Updated positioning of contextual help
* Added tooltip to form icon group remove

Update Form Icon Group

---

Jenkinsfile
functions.bash
player.sh
project.conf

Should prompt user to approve merge to develop

Adding merge to Dev

---

Jenkinsfile
Jenkinsfile.promotion

Per discussion with Jason, we're promoting master to Test automatically and Production on approval.
In an earlier PR I broke out promotion to a different Jenkinsfile so we could have IAM determine rights to the promotion phases.

Test is now latest master (unpromted) and Production is now latest master (prompted)

---

Jenkinsfile

I'll put in a cron job or somethin else instead

Removing cleanup

---

prime-angular-frontend/src/app/modules/adjudication/pages/enrolments/enrolments.component.html
prime-angular-frontend/src/app/modules/enrolment-certificate/pages/certificate/certificate.component.html
prime-angular-frontend/src/app/modules/enrolment-certificate/pages/certificate/certificate.component.ts
prime-angular-frontend/src/app/modules/enrolment/pages/access-agreement/access-agreement.component.html
prime-angular-frontend/src/app/modules/enrolment/pages/confirmation/confirmation.component.html
prime-angular-frontend/src/app/modules/enrolment/pages/device-provider/device-provider.component.html
prime-angular-frontend/src/app/modules/enrolment/pages/job/job.component.html
prime-angular-frontend/src/app/modules/enrolment/pages/organization/organization.component.html
prime-angular-frontend/src/app/modules/enrolment/pages/profile/profile.component.html
prime-angular-frontend/src/app/modules/enrolment/pages/profile/profile.component.scss
prime-angular-frontend/src/app/modules/enrolment/pages/regulatory/regulatory.component.html
prime-angular-frontend/src/app/modules/enrolment/pages/review/review.component.html
prime-angular-frontend/src/app/modules/enrolment/pages/self-declaration/self-declaration.component.html
prime-angular-frontend/src/app/modules/enrolment/pages/summary/summary.component.html
prime-angular-frontend/src/app/modules/enrolment/pages/summary/summary.component.scss
prime-angular-frontend/src/app/modules/enrolment/pages/summary/summary.component.ts
prime-angular-frontend/src/app/shared/components/clipboard-icon/clipboard-icon.component.html
prime-angular-frontend/src/app/shared/components/clipboard-icon/clipboard-icon.component.scss
prime-angular-frontend/src/app/shared/components/clipboard-icon/clipboard-icon.component.ts
prime-angular-frontend/src/app/shared/components/enrollee-review/enrollee-review.component.html
prime-angular-frontend/src/app/shared/components/forms/address/address.component.html
prime-angular-frontend/src/app/shared/components/page-subheader/page-subheader.component.scss
prime-angular-frontend/src/scss/material/_material-fixes.scss

* Updated layouts for enrolments
* Updated spacing of sections
* Updated clipboard component

Updated UX/UI

---

prime-dotnet-webapi/Models/Enrollee.cs
prime-dotnet-webapi/Services/DefaultEnrolleeService.cs

* Fix for current status check on enrollees
* Fix for enrollee applied and approved dates having mulitple results

Fixes for Enrollees/Enrollee

---

openshift/dotnet-webapi.dc.yaml
openshift/schemaspy.dc.yaml
prime-angular-frontend/nginx.template.conf

Some inconsistencies in templates.

Minor cleanup

---

prime-dotnet-webapi/appsettings.json

Local connection string got changed by accident, reverting.

Fix db connection string for local

---

openshift/dotnet-webapi.bc.yaml
openshift/dotnet-webapi.dc.yaml
openshift/postgresql.bc.yaml

fixing unresolved tokens

---

prime-angular-frontend/src/app/modules/enrolment/pages/organization/organization.component.ts

Enable Community Pharmacy Organization for Pilar

---

prime-angular-frontend/src/app/modules/enrolment/shared/components/college-certification-form/college-certification-form.component.html
prime-angular-frontend/src/app/modules/enrolment/shared/components/college-certification-form/college-certification-form.component.ts
prime-angular-frontend/src/app/shared/validators/form-control.validators.ts
prime-dotnet-webapi/Migrations/20200116191237_licenseNumber.Designer.cs
prime-dotnet-webapi/Migrations/20200116191237_licenseNumber.cs
prime-dotnet-webapi/Models/Certification.cs

Update licenseNumber of certification and college certification form to allow for alpha numeric characters of length > 1

PRIME-261: Alpha numeric college license numbers

---

prime-angular-frontend/src/app/modules/enrolment/shared/models/terms-of-access.model.ts

Got reverted to old version somehow during merges i think

terms-of-access model fixed

---

prime-angular-frontend/src/app/modules/auth/pages/info/info.component.html
prime-angular-frontend/src/app/shared/components/dialogs/confirm-dialog/confirm-dialog.component.html
prime-angular-frontend/src/scss/bootstrap/_bootstrap-variables.scss

* Fix image showing in dialog
* Fix font size

Fix Update

---

prime-angular-frontend/src/app/modules/auth/pages/info/info.component.html
prime-angular-frontend/src/app/modules/auth/pages/info/info.component.scss
prime-angular-frontend/src/app/shared/components/page-subheader/page-subheader.component.html
prime-angular-frontend/src/app/shared/components/page-subheader/page-subheader.component.scss
prime-angular-frontend/src/app/shared/components/page-subheader/page-subheader.component.ts

updated to use global font sizes, as well as adding the ability to remove divider from sub-header

fixes to login

---

prime-angular-frontend/src/app/shared/models/enrolment.model.ts
prime-angular-frontend/src/test/mocks/mock-enrolment.service.ts
prime-dotnet-webapi-tests/Mocks/AccessTermMockService.cs
prime-dotnet-webapi/Models/Enrollee.cs
prime-dotnet-webapi/Services/DefaultEnrolleeService.cs

Removing unneeded property on the enrollee model.

Remove Availible Statuses

---

prime-angular-frontend/src/app/modules/auth/pages/info/info.component.html

words turned into better words

login page words

---

prime-dotnet-webapi/Models/EnrolmentCertificate.cs

property was missed from PR#303

Remove DOB property

---

prime-dotnet-webapi/Dockerfile
prime-dotnet-webapi/openshift.dockerfile

In the interests of making release, and since we know 2.2 migrates properly, I am testing to determine if we can incorporate this in OpenShift with existing .NET version.

Attempting database migrations with 2.2

---

functions.bash

Artifacts were piling up.  Found that some of the returns were coming back a bit different.

Cleanup wasn't working

---

documentation/Keycloak settings/realm-export-prod.json
documentation/Keycloak settings/realm-export-test.json

Changed keycloak again to fix a bug or two

More Keycloak Documentation Updates

---

prime-dotnet-webapi/Controllers/EnrolleesController.cs

Add new endpoint only for testing email sending in prod

Add test endpoint

---

prime-dotnet-webapi/Controllers/EnrolleesController.cs

This reverts commit 623c8e40c0819f0e1ed4907dfbe693fc9bdc0188, removing the endpoint for testing email.

Revert email test endpoint

---

prime-angular-frontend/src/app/shared/components/enrollee/enrollee-review/enrollee-review.component.html

https://bcgovmoh.atlassian.net/browse/PRIME-419

Seperate college number from license number on review page

---

prime-angular-frontend/src/app/modules/adjudication/pages/enrollee-profile-version/enrollee-profile-version.component.html
prime-angular-frontend/src/app/modules/adjudication/pages/enrolment/enrolment.component.html
prime-angular-frontend/src/app/modules/enrolment/pages/overview/overview.component.html
prime-angular-frontend/src/app/modules/enrolment/pages/overview/overview.component.ts
prime-angular-frontend/src/app/modules/enrolment/shared/guards/enrolment.guard.ts
prime-angular-frontend/src/app/shared/components/dashboard/dashboard.component.ts
prime-angular-frontend/src/app/shared/components/enrollee/enrollee-review/enrollee-review.component.html
prime-angular-frontend/src/app/shared/components/enrollee/enrollee-review/enrollee-review.component.ts

* Allow enrollees to access their profile as read-only after submission

Allow Profile Access

---

prime-angular-frontend/src/app/modules/auth/pages/info/info.component.html
prime-angular-frontend/src/app/shared/components/prime-phone/prime-phone.component.ts
prime-angular-frontend/src/environments/environment.prod.template.ts
prime-angular-frontend/src/environments/environment.prod.ts
prime-angular-frontend/src/environments/environment.ts

* Updated phone in environment to contain dashes
* Updated phone component to allow for normal or vanity display

Phone Number Update

---

prime-angular-frontend/src/app/modules/auth/pages/info/info.component.html
prime-angular-frontend/src/app/modules/auth/pages/info/info.component.scss

* Larger buttons on landing page
* Light blue coloured button on landing page

Landing Page Buttons

---

prime-dotnet-webapi/Controllers/ProvisionerAccessController.cs

update not finished enrolment check

Email Provisioner Link fix

---

documentation/Keycloak settings/realm-export-dev.json
documentation/Keycloak settings/realm-export-test.json
prime-dotnet-webapi/PrimeConstants.cs

Updating keycloak export for new super admin role

Update Keycloak Export

---

prime-angular-frontend/src/app/modules/adjudication/pages/limits-conditions-clauses/limits-conditions-clauses.component.html
prime-angular-frontend/src/app/modules/enrolment/pages/access-agreement/components/access-term/access-term.component.ts

Text Change to TOA

---

prime-angular-frontend/src/app/modules/adjudication/pages/adjudicator-notes/adjudicator-notes.component.html
prime-angular-frontend/src/app/modules/adjudication/pages/adjudicator-notes/adjudicator-notes.component.ts
prime-angular-frontend/src/app/modules/adjudication/pages/enrolments/enrolments.component.html
prime-angular-frontend/src/app/modules/adjudication/pages/enrolments/enrolments.component.ts
prime-angular-frontend/src/app/modules/adjudication/pages/limits-conditions-clauses/limits-conditions-clauses.component.html
prime-angular-frontend/src/app/modules/adjudication/pages/limits-conditions-clauses/limits-conditions-clauses.component.ts
prime-angular-frontend/src/app/modules/auth/pages/info/info.component.html
prime-angular-frontend/src/app/modules/enrolment/pages/collection-notice/collection-notice.component.spec.ts
prime-angular-frontend/src/app/modules/enrolment/pages/overview/overview.component.html
prime-angular-frontend/src/app/modules/enrolment/shared/components/collection-notice-alert/collection-notice-alert.component.spec.ts
prime-angular-frontend/src/app/shared/components/enrollee/enrollee-review/enrollee-review.component.html
prime-dotnet-webapi/Controllers/EnrolleesAccessTermsController.cs
prime-dotnet-webapi/Controllers/EnrolleesController.cs

* Only allow addition of limits and conditions when under review
* Random updates to text

Limits and Conditions Clause Only Under Review

---

prime-dotnet-webapi/Services/EnrolleeService.cs

GPID is re-generated on every submission. We should not do that.

Fix GPID generation

---

prime-dotnet-webapi/Controllers/EnrolleesController.cs
prime-dotnet-webapi/Models/Api/ApiOkResponse.cs
prime-dotnet-webapi/Services/EmailService.cs
prime-dotnet-webapi/Services/EnrolleeService.cs

This reverts commit ac944a1723bea03f4bb5ad93fa473243ab73800e.

Revert "Feature/email fail gracefully back end (#404)"

---

prime-dotnet-webapi/Controllers/EnrolleesController.cs
prime-dotnet-webapi/Extensions/ClaimsPrincipalExensions.cs
prime-dotnet-webapi/Infrastructure/PrimeUserAuthHandler.cs

New extension for admins, makes things a little cleaner.

New Extension

---

prime-angular-frontend/src/app/modules/adjudication/pages/enrolments/enrolments.component.html
prime-angular-frontend/src/app/modules/adjudication/pages/enrolments/enrolments.component.ts
prime-angular-frontend/src/app/modules/enrolment/pages/pharmanet-enrolment-summary/pharmanet-enrolment-summary.component.html
prime-angular-frontend/src/app/shared/models/enrolment.model.ts
prime-dotnet-webapi/Models/Enrollee.cs

Depending if this or search gets merged first the search will have to be updated to reference this derived column

derived display id and display of id

---

Jenkinsfile
Jenkinsfile.promotion
functions.bash

Fixed pipeline script order

---

prime-dotnet-webapi/Services/PharmanetAPIService.cs

Fix API Logging

---

prime-angular-frontend/src/app/core/services/error-handler.service.ts
prime-angular-frontend/src/app/modules/adjudication/pages/enrolments/enrolments.component.ts
prime-angular-frontend/src/app/modules/adjudication/shared/services/adjudication-resource.service.ts

* Fix enrolment refresh throwing an error when status is `All` on initial load

Fix Enrolment Refresh

---

Jenkinsfile
Jenkinsfile.promotion
functions.bash
openshift/schemaspy.bc.yaml
openshift/schemaspy.dc.yaml
sonar-scanner/openshift.dockerfile
sonar-scanner/sonar-runner.cmd
sonar-scanner/sonar-runner.local
sonarQube.cmd
tests.bash

Upgraded to .NET 3.1 on sonar-scanner
Added parallel build steps to dev
Fixed some bad environment variables

Build and Test improvements

---

documentation/Keycloak settings/realm-export-dev.json
documentation/Keycloak settings/realm-export-prod.json

Keycloak updates

---

prime-dotnet-webapi/Models/BusinessEventType.cs
prime-dotnet-webapi/Services/BusinessEventService.cs
prime-dotnet-webapi/Services/EnrolleeService.cs
prime-dotnet-webapi/Services/SubmissionService.cs
prime-dotnet-webapi/Services/interfaces/IBusinessEventService.cs

* Added Enrollee Created event
* Updated Disclaim event
* Changed location of Submitted event

Event Update

---

prime-angular-frontend/src/app/modules/auth/pages/info/info.component.html

PRIME-553 - Updated casing on card

---

prime-dotnet-webapi/Configuration/StatusReasonConfiguration.cs
prime-dotnet-webapi/Migrations/20200318214149_UpdateStatusReasons.Designer.cs
prime-dotnet-webapi/Migrations/20200318214149_UpdateStatusReasons.cs

Updates the text on status reasons.

PRIME-550 - Update Status Reasons

---

prime-angular-frontend/src/app/modules/adjudication/pages/adjudicator-notes/adjudicator-notes.component.ts
prime-angular-frontend/src/app/modules/adjudication/shared/components/dated-content-table/dated-content-table.component.html
prime-angular-frontend/src/app/modules/adjudication/shared/components/dated-content-table/dated-content-table.component.ts
prime-angular-frontend/src/app/modules/adjudication/shared/components/enrollee-table/enrollee-table.component.html
prime-angular-frontend/src/app/modules/adjudication/shared/models/adjudication-note.model.ts
prime-angular-frontend/src/app/shared/pipes/replace.pipe.ts
prime-dotnet-webapi/Configuration/AdjudicatorNoteConfiguration.cs
prime-dotnet-webapi/Controllers/EnrolleesController.cs
prime-dotnet-webapi/Migrations/20200319200528_AddedAdjudicatorToNote.Designer.cs
prime-dotnet-webapi/Migrations/20200319200528_AddedAdjudicatorToNote.cs
prime-dotnet-webapi/Models/Admin.cs
prime-dotnet-webapi/Models/Notes/AdjudicatorNote.cs
prime-dotnet-webapi/Services/EnrolleeService.cs
prime-dotnet-webapi/Services/interfaces/IEnrolleeService.cs

* Updated adjudicator to be stored on adjudication notes
* Updated adjudicator idir to be displayed in the notes view
* Updated adjudicator assignment by moving out admin query to controller

PRIME-535 - Adjudicator Name on Created Notes

---

prime-angular-frontend/src/app/modules/auth/pages/info/info.component.html
prime-angular-poc/package-lock.json
prime-angular-poc/yarn.lock

Fixed the triggers for the security

PRIME-577 - Front-end security hardening

---

prime-angular-frontend/src/app/modules/adjudication/shared/components/enrollee-table/enrollee-table.component.html
prime-angular-frontend/src/app/modules/adjudication/shared/components/enrollee-table/enrollee-table.component.ts
prime-dotnet-webapi/Models/Enrollee.cs
prime-dotnet-webapi/Services/AccessTermService.cs
prime-dotnet-webapi/Services/EnrolleeService.cs
prime-dotnet-webapi/Services/interfaces/IAccessTermService.cs

attached to the enrollee object that the enrollee has signed the most recent ToA when the call is made for the admin side of thing. Not sure what verbage to use so just made it super simple for now.

PRIME-567-most-recent-toa

---

prime-dotnet-webapi/Services/EmailService.cs

PRIME-589 update clinic email

---

prime-angular-frontend/openshift.dockerfile

* Updated openshift build to force version of angular devkit

PRIME-# - Fix for npm audit fix

---

prime-dotnet-webapi/AuthConstants.cs
prime-dotnet-webapi/AuthenticationSetup.cs
prime-dotnet-webapi/Controllers/AdminsController.cs
prime-dotnet-webapi/Controllers/EnrolleesAccessTermsController.cs
prime-dotnet-webapi/Controllers/EnrolleesController.cs
prime-dotnet-webapi/Controllers/FeedbackController.cs
prime-dotnet-webapi/Controllers/LookupsController.cs
prime-dotnet-webapi/Controllers/ProvisionerAccessController.cs
prime-dotnet-webapi/Controllers/SubmissionsController.cs
prime-dotnet-webapi/Extensions/ClaimsPrincipalExtensions.cs
prime-dotnet-webapi/Infrastructure/PrimeUserAuthHandler.cs
prime-dotnet-webapi/PrimeConstants.cs
prime-dotnet-webapi/Startup.cs

break auth constants out into their own file

PRIME-510 - Auth Constants

---

prime-angular-frontend/src/app/modules/adjudication/pages/enrollee-events/enrollee-events.component.html
prime-angular-frontend/src/app/modules/adjudication/pages/enrollee-events/enrollee-events.component.ts
prime-angular-frontend/src/app/modules/adjudication/shared/components/adjudication-container/adjudication-container.component.ts
prime-angular-frontend/src/app/shared/components/collection-notice-alert/collection-notice-alert.component.html

* Refresh the events when a note is created using a dialog on that page

PRIME-618 - Refresh Events

---

README.md

I was going to commit direct but then I'd never hear the end of it.

PRIME-642 Update README.md

---

prime-dotnet-webapi/Controllers/ProvisionerAccessController.cs
prime-dotnet-webapi/Models/Api/HpdidLookupResponse.cs
prime-dotnet-webapi/Services/EnrolleeService.cs
prime-dotnet-webapi/Services/interfaces/IEnrolleeService.cs

API now supports supplying a list of hpdids, and returns a list that now includes the renewal date.
See https://bcgovmoh.atlassian.net/browse/PRIME-640 for updated documentation

PRIME-640 - Update CareConnect Lookup

---

prime-dotnet-webapi/Dockerfile

PRIME-657 Found a missing package

---

prime-dotnet-webapi/.gitignore
prime-dotnet-webapi/.vscode/settings.json
prime-dotnet-webapi/ApiDbContext.cs
prime-dotnet-webapi/Extensions/ClaimsPrincipalExtensions.cs
prime-dotnet-webapi/PrimeConstants.cs
prime-dotnet-webapi/Program.cs
prime-dotnet-webapi/Services/EmailService.cs
prime-dotnet-webapi/Startup.cs
prime-dotnet-webapi/appsettings.Development.json
prime-dotnet-webapi/appsettings.json
prime-dotnet-webapi/prime.csproj

**General Logging Examples**
_Normal Log (prime.log)_
```
[00:51:44 INF] Starting web host
[00:51:46 INF] Now listening on: https://localhost:5001
[00:51:46 INF] Now listening on: http://localhost:5000
[00:51:46 INF] Application started. Press Ctrl+C to shut down.
[00:51:46 INF] Hosting environment: Development
[00:51:46 INF] Content root path: /Users/mtpultz/Projects/moh-prime/prime-dotnet-webapi
[00:52:13 INF] HTTP OPTIONS /api/lookups responded 204 in 71.02207 ms
[00:52:13 INF] HTTP OPTIONS /api/enrollees responded 204 in 70.570075 ms
[00:52:18 INF] HTTP GET /api/lookups responded 200 in 4960.743221 ms
[00:52:18 INF] HTTP GET /api/enrollees responded 200 in 4968.136654 ms
```
_JSON Log (prime.json)_
Abridged to a single request, but the properties are similar, and it adds the PRIME …

PRIME-506 - Logging

---

prime-angular-frontend/src/app/modules/enrolment/enrolment-routing.module.ts
prime-angular-frontend/src/app/modules/enrolment/pages/access-agreement-history/access-agreement-history.component.spec.ts
prime-angular-frontend/src/app/modules/enrolment/pages/access-agreement/access-agreement.component.spec.ts
prime-angular-frontend/src/app/modules/enrolment/pages/access-agreement/access-agreement.component.ts
prime-angular-frontend/src/app/modules/enrolment/pages/access-declined/access-declined.component.html
prime-angular-frontend/src/app/modules/enrolment/pages/access-declined/access-declined.component.spec.ts
prime-angular-frontend/src/app/modules/enrolment/pages/access-locked/access-locked.component.html
prime-angular-frontend/src/app/modules/enrolment/pages/demographic/demographic.component.html
prime-angular-frontend/src/app/modules/enrolment/pages/device-provider/device-provider.component.html
prime-angular-frontend/src/app/modules/enrolment/pages/job/job.component.html
prime-angular-frontend/src/app/modules/enrolment/pages/minor-update-confirmation/minor-update-confirmation.component.html
prime-angular-frontend/src/app/modules/enrolment/pages/organization/organization.component.html
prime-angular-frontend/src/app/modules/enrolment/pages/organization/organization.component.spec.ts
prime-angular-frontend/src/app/modules/enrolment/pages/overview/overview.component.html
prime-angular-frontend/src/app/modules/enrolment/pages/regulatory/regulatory.component.html
prime-angular-frontend/src/app/modules/enrolment/pages/self-declaration/self-declaration.component.html
prime-angular-frontend/src/app/modules/enrolment/pages/submission-confirmation/submission-confirmation.component.html
prime-angular-frontend/src/app/modules/provisioner-access/shared/components/provisioner-access/provisioner-access.component.spec.ts
prime-angular-frontend/src/app/modules/site-registration/pages/organization-agreement/organization-agreement.component.spec.ts
prime-angular-frontend/src/app/modules/site-registration/pages/site-address/site-address.component.spec.ts

* Replace PRIME profile or PharmaNet Enrolment with PRIME Enrolment

PRIME-656 - PRIME Enrolment

---

prime-angular-frontend/src/app/modules/enrolment/enrolment-routing.module.ts
prime-angular-frontend/src/app/modules/enrolment/enrolment.module.ts
prime-angular-frontend/src/app/modules/enrolment/enrolment.routes.ts
prime-angular-frontend/src/app/modules/enrolment/pages/notification-confirmation/notification-confirmation.component.html
prime-angular-frontend/src/app/modules/enrolment/pages/notification-confirmation/notification-confirmation.component.scss
prime-angular-frontend/src/app/modules/enrolment/pages/notification-confirmation/notification-confirmation.component.spec.ts
prime-angular-frontend/src/app/modules/enrolment/pages/notification-confirmation/notification-confirmation.component.ts
prime-angular-frontend/src/app/modules/enrolment/pages/pharmanet-enrolment-summary/pharmanet-enrolment-summary.component.ts
prime-angular-frontend/src/app/modules/enrolment/shared/components/enrollee-page/enrollee-page.component.html
prime-angular-frontend/src/app/modules/enrolment/shared/components/enrollee-page/enrollee-page.component.scss
prime-angular-frontend/src/app/modules/enrolment/shared/components/enrollee-page/enrollee-page.component.ts
prime-angular-frontend/src/app/modules/enrolment/shared/components/enrolment-progress-indicator/enrolment-progress-indicator.component.html
prime-angular-frontend/src/app/modules/enrolment/shared/components/enrolment-progress-indicator/enrolment-progress-indicator.component.ts
prime-angular-frontend/src/app/modules/site-registration/shared/components/site-progress-indicator/site-progress-indicator.component.html
prime-angular-frontend/src/app/modules/site-registration/shared/components/site-progress-indicator/site-progress-indicator.component.ts
prime-angular-frontend/src/app/shared/components/dialogs/confirm-dialog/confirm-dialog.component.ts
prime-angular-frontend/src/app/shared/components/dialogs/content/feedback/feedback.component.html
prime-angular-frontend/src/app/shared/components/dialogs/content/feedback/feedback.component.ts
prime-angular-frontend/src/app/shared/components/dialogs/dialog-output.model.ts
prime-angular-frontend/src/app/shared/services/feedback-resource.service.ts

* Added notification confirmation view
* Feedback only on notification confirmation view

PRIME-714/715 - Notification Submission / Feedback

---

prime-dotnet-webapi-tests/ModelFactories/CertificationFactory.cs
prime-dotnet-webapi-tests/ModelFactories/EnrolleeFactory.cs
prime-dotnet-webapi-tests/ModelFactories/NoteFactory.cs
prime-dotnet-webapi-tests/Services/AutomaticAdjudicationRules.Tests.cs

Breaking up the testing updates into multiple PRs
This PR starts using the Model factories. Some updates were required. Changed around the automatic rules tests.

PRIME-625 - First part of test updates

---

prime-dotnet-webapi-tests/Mocks/BusinessEventServiceMock.cs
prime-dotnet-webapi-tests/Mocks/EmailServiceMock.cs
prime-dotnet-webapi-tests/Services/EnrolmentCertificateService.Tests.cs
prime-dotnet-webapi/Controllers/ProvisionerAccessController.cs
prime-dotnet-webapi/Models/EnrolmentCertificate.cs
prime-dotnet-webapi/Models/EnrolmentCertificateAccessToken.cs
prime-dotnet-webapi/Models/SiteRegistration/Vendor.cs
prime-dotnet-webapi/Services/EmailService.cs
prime-dotnet-webapi/Services/EnrolmentCertificateService.cs
prime-dotnet-webapi/Services/interfaces/IEmailService.cs
prime-dotnet-webapi/Services/interfaces/IEnrolmentCertificateService.cs
prime-dotnet-webapi/Views/Emails/VendorEmail.cshtml

Removes max views for a provisioner link.
Also moved some parameters around. Vendor emails are in the database now, and getting the emails in now in the email service.

PRIME-556 - Remove Provisioner Link Max Views

---

prime-dotnet-webapi/Views/Emails/OfficeManagerEmail.cshtml

PRIME-556 - Missed line from email

---

prime-angular-frontend/src/app/shared/components/dashboard/dashboard.component.ts

* Provide the site registration links to the user in the dashboard
NOTE: Update omits sections of the acceptance criteria since it doesn't represent a single or multiple site registrations appropriately, and only addresses single site initial registration.  Further work on this ticket would be refactored completely before the end of the sprint

PRIME-762 - Site Registration Dashboard Navigation

---

prime-angular-frontend/src/app/modules/auth/pages/site/site.component.html
prime-angular-frontend/src/app/modules/auth/shared/styles/landing-page.scss

* Added newer updates to the new updates

PRIME-671 - Landing Page (Version 2)

---

Jenkinsfile.promotion

Need to increase Jenkins pipeline timeouts

increasing pipeline timeout

---

openshift/metabase.dc.yaml

Unexpected, interrupted upgrade broke metabase.
This PR fixes it.

PRIME-812 - Fix Metabase

---

prime-angular-frontend/src/app/modules/enrolment/pages/organization/organization.component.html
prime-angular-frontend/src/app/modules/enrolment/pages/organization/organization.component.ts
prime-angular-frontend/src/app/modules/enrolment/shared/services/enrolment-state.service.ts
prime-angular-frontend/src/app/shared/components/enrollee/enrollee-review/enrollee-review.component.html
prime-angular-frontend/src/app/shared/components/enrollee/enrollee-review/enrollee-review.component.ts
prime-angular-frontend/src/app/shared/models/enrolment.model.ts
prime-dotnet-webapi/Configuration/StatusReasonConfiguration.cs
prime-dotnet-webapi/Migrations/20200602072737_RequestingRemoteAccess.Designer.cs
prime-dotnet-webapi/Migrations/20200602072737_RequestingRemoteAccess.cs
prime-dotnet-webapi/Migrations/20200602075314_RequestingRemoteAccessRuleSeed.Designer.cs
prime-dotnet-webapi/Migrations/20200602075314_RequestingRemoteAccessRuleSeed.cs
prime-dotnet-webapi/Migrations/20200602213903_RequestingRemoteAccessSeed.Designer.cs
prime-dotnet-webapi/Migrations/20200602213903_RequestingRemoteAccessSeed.cs
prime-dotnet-webapi/Models/Enrollee.cs
prime-dotnet-webapi/Models/Statuses/StatusReasonType.cs
prime-dotnet-webapi/Services/Rules/AutomaticAdjudicationRules.cs
prime-dotnet-webapi/Services/SubmissionRulesService.cs
prime-dotnet-webapi/ViewModels/Enrollee/EnrolleeProfileViewModel.cs

Requesting Remote Access.
Not sure if isObo is reliable enough for it only to show for a RU

PRIME-747 Remote Access

---

documentation/Keycloak settings/realm-export-dev.json
documentation/Keycloak settings/realm-export-prod.json
documentation/Keycloak settings/realm-export-test.json

Disabling back channel logout should hopefully fix the annoying error screen when logging out.
Dev test and prod Keycloak have been updated, this is just documentation.

Fix Logout Bug

---

prime-dotnet-webapi/Controllers/EnrolleesController.cs
prime-dotnet-webapi/Services/SubmissionService.cs
prime-dotnet-webapi/Services/interfaces/ISubmissionService.cs

Endpoint to check all enrollees gpids and update if invalid

PRIME-746 - Update existing non HL7 compliant gpids

---

docker-compose.yml

Update docman Dockerfile

---

documentation/Keycloak settings/realm-export-dev.json
documentation/Keycloak settings/realm-export-prod.json
documentation/Keycloak settings/realm-export-test.json

The Community Pharmacy feature flag is now enabled to all users in DEV and TEST.
Kecyloak documentation has been updated,

PRIME-879 - Enable Comunity Pharmacy in Dev/Test

---

prime-dotnet-webapi/Configuration/AccessTerms/UserClauseConfiguration.cs
prime-dotnet-webapi/Migrations/20200715215356_FixOboToa.Designer.cs
prime-dotnet-webapi/Migrations/20200715215356_FixOboToa.cs

The current newest RU TOA was accidentally assigned to OBOs

Fix OBO TOA

---

prime-dotnet-webapi/Controllers/EnrolleesController.cs
prime-dotnet-webapi/Services/SubmissionService.cs
prime-dotnet-webapi/Services/interfaces/ISubmissionService.cs

Removes the temporary endpoint added to modify prod GPIDs that were not compliant.

Revert GPID Update Endpoint 

---

Jenkinsfile
openshift/document-manager-ephemeral.dc.yaml
openshift/postgresql.ephemeral.dc.yaml

Removing PVC from Ephemeral template

Remove PVC

---

prime-dotnet-webapi-tests/ModelFactories/EnrolleeFactory.cs
prime-dotnet-webapi-tests/Unit Tests/EmailService.Tests.cs
prime-dotnet-webapi-tests/Unit Tests/EnrolmentCertificateService.Tests.cs
prime-dotnet-webapi-tests/Unit Tests/SubmissionService.Tests.cs

PRIME # - Unbreak backend tests

---

prime-dotnet-webapi/AuthenticationSetup.cs
prime-dotnet-webapi/Infrastructure/EmptyStringToNullJsonConverter.cs
prime-dotnet-webapi/Infrastructure/PrimeUserAuthHandler.cs
prime-dotnet-webapi/Services/AdminService.cs
prime-dotnet-webapi/Services/Clients/College Licence API/CollegeLicenceClient.cs
prime-dotnet-webapi/Services/EnrolleeService.cs
prime-dotnet-webapi/Services/OrganizationService.cs
prime-dotnet-webapi/Services/PartyService.cs
prime-dotnet-webapi/Services/SiteService.cs
prime-dotnet-webapi/Services/SubmissionService.cs

Using .ThrowIfNull() to simplify some code.

Use ThrowIfNull

---

Jenkinsfile
Jenkinsfile.production
Jenkinsfile.promotion
Jenkinsfile.test
Jenkinsfile.tools
player.sh

Removing all but the parent and template directories on each run

Trying to mitigate space issues

---

documentation/Keycloak settings/realm-export-dev.json

Dev keycloak has been updated, so the new dev export has been updated as well.
Nothing material should have changed, but the export is in a different order so the diff looks like stuff has changed.

Update Keycloak Dev Documentation

---

prime-angular-frontend/src/app/modules/site-registration/pages/care-setting/care-setting.component.ts
prime-angular-frontend/src/app/modules/site-registration/pages/hours-operation/hours-operation.component.html
prime-angular-frontend/src/app/modules/site-registration/pages/hours-operation/hours-operation.component.ts
prime-angular-frontend/src/app/modules/site-registration/pages/organization-agreement/organization-agreement.component.ts
prime-angular-frontend/src/app/modules/site-registration/pages/overview/overview.component.ts
prime-angular-frontend/src/app/modules/site-registration/pages/remote-users/remote-users.component.html
prime-angular-frontend/src/app/modules/site-registration/pages/remote-users/remote-users.component.ts
prime-angular-frontend/src/app/modules/site-registration/pages/site-management/site-management.component.html
prime-angular-frontend/src/app/modules/site-registration/pages/site-management/site-management.component.ts
prime-angular-frontend/src/app/modules/site-registration/pages/technical-support/technical-support.component.ts
prime-angular-frontend/src/app/modules/site-registration/shared/guards/registration.guard.ts
prime-angular-frontend/src/app/modules/site-registration/shared/guards/site.guard.ts
prime-angular-frontend/src/app/modules/site-registration/shared/services/organization.service.ts
prime-angular-frontend/src/app/modules/site-registration/site-registration-routing.module.ts

* Fix Add Site being repeated for every site
* Fix technical support route always going to remote users, and not review
* Add busy blocker to hours of operation
* Add busy blocker to remote users
* Temporary fix for query params being wiped during routes

PRIME 1022 - Site Registration Updates/Fixes

---

prime-dotnet-webapi-tests/Mocks/EmailServiceMock.cs
prime-dotnet-webapi-tests/Unit Tests/EnrolmentCertificateService.Tests.cs

Some backend tests are broken.

Fix Backend Tests

---

prime-angular-frontend/src/app/lib/classes/abstract-form-state.class.ts
prime-angular-frontend/src/app/lib/types/address-line.type.ts
prime-angular-frontend/src/app/modules/adjudication/shared/components/adjudication-dashboard/adjudication-dashboard.component.html
prime-angular-frontend/src/app/modules/adjudication/shared/components/adjudication-dashboard/adjudication-dashboard.component.ts
prime-angular-frontend/src/app/modules/enrolment/enrolment-routing.module.ts
prime-angular-frontend/src/app/modules/enrolment/pages/bceid-demographic/bceid-demographic.component.ts
prime-angular-frontend/src/app/modules/enrolment/pages/care-setting/care-setting.component.ts
prime-angular-frontend/src/app/modules/enrolment/pages/overview/overview.component.html
prime-angular-frontend/src/app/modules/enrolment/pages/overview/overview.component.scss
prime-angular-frontend/src/app/modules/enrolment/pages/overview/overview.component.ts
prime-angular-frontend/src/app/modules/enrolment/pages/regulatory/regulatory.component.ts
prime-angular-frontend/src/app/modules/enrolment/pages/remote-access/remote-access.component.html
prime-angular-frontend/src/app/modules/enrolment/pages/remote-access/remote-access.component.ts
prime-angular-frontend/src/app/modules/enrolment/pages/self-declaration/self-declaration.component.html
prime-angular-frontend/src/app/modules/enrolment/pages/self-declaration/self-declaration.component.ts
prime-angular-frontend/src/app/modules/enrolment/shared/services/enrolment-form-state.service.ts
prime-angular-frontend/src/app/modules/site-registration/pages/remote-user/remote-user.component.ts
prime-angular-frontend/src/app/modules/site-registration/pages/site-address/site-address.component.ts
prime-angular-frontend/src/app/modules/site-registration/shared/components/site-registration-dashboard/site-registration-dashboard.component.html
prime-angular-frontend/src/app/modules/site-registration/shared/components/site-registration-dashboard/site-registration-dashboard.component.ts
prime-angular-frontend/src/app/modules/site-registration/shared/services/site-form-state.service.ts
prime-angular-frontend/src/app/shared/components/enrollee/enrollee-review/enrollee-review.component.ts
prime-angular-frontend/src/app/shared/components/forms/address/address.component.ts

- Ported changes from PROD
- Fix enrolment routing
- Show remote user access on refresh/reload if chosen
- Added missing input bindings for logout redirect
- Added redirect to demographic for BCeID
- Fix for BCeID not allowing province being set

PRIME-1135 Updates/Fixes Enrolments and Site Registration

---

prime-dotnet-webapi/Engines/AgreementEngine.cs
prime-dotnet-webapi/Services/AgreementService.cs

PRIME-1162 - Agreement Engine

---

documentation/Keycloak settings/realm-export-dev.json
documentation/Keycloak settings/realm-export-prod.json
documentation/Keycloak settings/realm-export-test.json

Main update is new feature flag for health authorities in dev/test/prod. New Mapper to assign said feature flag in dev/test.

Update Keycloak Documentation

---

prime-angular-frontend/src/app/modules/enrolment/pages/overview/overview.component.ts
prime-angular-frontend/src/app/modules/enrolment/pages/remote-access/remote-access.component.ts
prime-angular-frontend/src/app/modules/enrolment/shared/guards/enrolment.guard.ts

* Fixes two bugs when enrollee are renewing

Read Enrollee Information from FormStateService for Renewals

---

docker-compose.yml
documentation/compositions/json/dotnet-webapi.bc.json
documentation/compositions/json/dotnet-webapi.dc.json
documentation/compositions/yaml/dotnet-webapi-deploymentconfig.yaml
openshift/dotnet-webapi.bc.yaml
openshift/dotnet-webapi.dc.yaml
prime-dotnet-webapi-tests/Utils/TestUtils.cs
prime-dotnet-webapi/AuthConstants.cs
prime-dotnet-webapi/AuthenticationSetup.cs
prime-dotnet-webapi/PrimeEnvironment.cs
prime-dotnet-webapi/Program.cs
prime-dotnet-webapi/appsettings.json
prime-dotnet-webapi/docker-compose.yml

Drop some unused environment variables from the API

Prune Environment Variables

---

prime-dotnet-webapi/.editorconfig

Omnisharp ignore all Migration files

Slight Change to EditorConfig

---

documentation/Keycloak settings/realm-export-dev.json
documentation/Keycloak settings/realm-export-prod.json
documentation/Keycloak settings/realm-export-test.json

Documentation update covering:
1. Addition of Care Connect client and Pharmacy feature flag in prod
2. Addition of Service Account client in Dev
3. Addition of pos-gpid client in test and prod

Keycloak Documentation Update

---

prime-angular-frontend/README.md
prime-angular-frontend/src/app/config/config.model.ts
prime-angular-frontend/src/app/shared/components/college-certification-form/college-certification-form.component.html
prime-angular-frontend/src/app/shared/components/college-certification-form/college-certification-form.component.ts
prime-dotnet-webapi/Models/Certifications/License.cs
prime-dotnet-webapi/README.md

This reverts commit 8aa4347a4e63e6f1ea4f7e8a4ec9c79430047bb5.

Revert "PRIME-1296 restrict college license entry (#1027)"

---

prime-angular-frontend/src/app/app-config.module.ts
prime-angular-frontend/src/app/modules/auth/shared/enum/role.enum.ts
prime-angular-frontend/src/app/modules/auth/shared/guards/authorization-redirect.guard.ts
prime-angular-frontend/src/app/modules/auth/shared/services/auth.service.ts
prime-angular-frontend/src/app/modules/phsa-labtech/phsa-labtech-routing.module.ts
prime-angular-frontend/src/app/modules/phsa-labtech/phsa-labtech.module.ts
prime-angular-frontend/src/app/modules/phsa-labtech/phsa-labtech.routes.ts

* Added new roles
* Updated to redirect appropriately when PHSA
* Updated route to distinguish the PHSA module from the Auth module to prevent infinite route loop when attempting to access the root route ('') of the PHSA Labtech module

PRIME-1330 Fix for PHSA redirects

---

prime-dotnet-webapi/Extensions/DictionaryExtensions.cs
prime-dotnet-webapi/HttpClients/Address Autocomplete/AddressAutocompleteClient.cs
prime-dotnet-webapi/HttpClients/College Licence API/CollegeLicenceClient.cs
prime-dotnet-webapi/HttpClients/Document Manager/DocumentManagerClient.cs
prime-dotnet-webapi/HttpClients/Email/CHESClient.cs

Using the BaseClient for the other clients plus some other minor refactoring.

Refactor Base Clients

---

prime-angular-frontend/src/app/modules/site-registration/pages/business-licence/business-licence.component.ts
prime-angular-frontend/src/app/modules/site-registration/pages/organization-name/organization-name.component.html

* Update org name displayed orgbook that was displaying the form group clear (X) icon
* Update bus licence validation to not show both validation messages when only a single error exists

Updated orgbook displayed and business licence validations

---

prime-angular-frontend/src/app/modules/adjudication/shared/components/site-registration-container/site-registration-container.component.html
prime-angular-frontend/src/app/modules/adjudication/shared/components/site-registration-container/site-registration-container.component.ts
prime-angular-frontend/src/app/modules/adjudication/shared/components/site-registration-table/site-registration-table.component.html
prime-angular-frontend/src/app/modules/adjudication/shared/components/site-registration-table/site-registration-table.component.ts
prime-angular-frontend/src/app/shared/components/dialogs/content/send-email/send-email.component.html
prime-angular-frontend/src/app/shared/components/dialogs/content/send-email/send-email.component.scss
prime-angular-frontend/src/app/shared/components/dialogs/content/send-email/send-email.component.spec.ts
prime-angular-frontend/src/app/shared/components/dialogs/content/send-email/send-email.component.ts
prime-angular-frontend/src/app/shared/shared.module.ts

- created send email dialog component for site registration admin

PRIME-1273 Send email on admin (site registration)

---

prime-dotnet-webapi-tests/ModelFactories/Lookups/CollegeLookup.cs
prime-dotnet-webapi-tests/Unit Tests/EnrolleeService.Tests.cs
prime-dotnet-webapi-tests/Unit Tests/RazorConverterService.Tests.cs
prime-dotnet-webapi-tests/Utils/TestUtils.cs
prime-dotnet-webapi/Models/Api/GpidValidation.cs
prime-dotnet-webapi/Services/EnrolleeService.cs

Some tests were broken due to the College License Prefix changes.
Also added test cases for the new site emails.

College Licence Testing Fixes

---

prime-dotnet-webapi/PrimeEnvironment.cs

Small refactor to reduce code duplication. Lets see where else we can apply this.

Using Static

---

prime-dotnet-webapi/Services/EmailService.cs

Easiest way to test is to use temporary `EmailsControllers` changes found in PR #1077 comments to invoke renewal emails algorithm and then manipulate `ExpiryDate` value in `Agreement` table so that emails are triggered

Fix for defect related to renewal emails

---

documentation/Keycloak settings/realm-export-dev.json
prime-dotnet-webapi/Auth/AuthConstants.cs

Really simple PR enumerating the new roles added to DEV keycloak

PRIME-1275 - New Roles

---

documentation/Keycloak settings/realm-export-dev.json
prime-dotnet-webapi/Auth/AuthConstants.cs

Picked a better name for the cohort of users that can access the "admin" side of our app, irrespective of their access level.

Update Role Name

---

prime-angular-frontend/src/app/modules/enrolment/shared/components/next-steps-infographic/next-steps-infographic.component.html
prime-angular-frontend/src/app/shared/components/forms/college-certification-form/college-certification-form.component.html

* Text update
* Pulled over fix for next steps from Address PR

PRIME-1384 Updates

---

prime-dotnet-webapi/Configuration/StatusReasonConfiguration.cs
prime-dotnet-webapi/Migrations/20210211233623_CollegeReasonText.Designer.cs
prime-dotnet-webapi/Migrations/20210211233623_CollegeReasonText.cs
prime-dotnet-webapi/Models/Certifications/Certification.cs
prime-dotnet-webapi/Services/Rules/AutomaticAdjudicationRules.cs

Update wording for Status Reasons related to College Licences

PRIME-1412 - Update to College Licence Status Reasons Text

---

prime-dotnet-webapi/Controllers/LookupsController.cs
prime-dotnet-webapi/HttpClients/College Licence API/CollegeLicenceClient.cs
prime-dotnet-webapi/HttpClients/College Licence API/DummyCollegeLicenceClient.cs
prime-dotnet-webapi/HttpClients/College Licence API/ICollegeLicenceClient.cs
prime-dotnet-webapi/HttpClients/College Licence API/PharmanetCollegeApiDefinitions.cs
prime-dotnet-webapi/HttpClients/Mail/Email.cs
prime-dotnet-webapi/Services/Rules/AutomaticAdjudicationRules.cs

Moving things around to make the College Licence client more like the other clients

Separate Pharmanet College API Definitions

---

prime-angular-frontend/src/app/core/services/form-utils.service.ts
prime-angular-frontend/src/app/lib/classes/abstract-form-state-service.class.ts
prime-angular-frontend/src/app/lib/types/address-line.type.ts
prime-angular-frontend/src/app/modules/enrolment/pages/bceid-demographic/bceid-demographic.component.ts
prime-angular-frontend/src/app/modules/site-registration/pages/remote-user/remote-user.component.ts
prime-angular-frontend/src/app/modules/site-registration/pages/site-address/site-address.component.ts
prime-angular-frontend/src/app/modules/site-registration/pages/site-management/site-management.component.ts
prime-angular-frontend/src/app/shared/components/address-view/address-view.component.ts
prime-angular-frontend/src/app/shared/components/forms/address-form/address-form.component.ts
prime-angular-frontend/src/app/shared/models/address.model.ts
prime-angular-frontend/src/app/shared/pipes/address.pipe.ts
prime-dotnet-webapi/Models/Addresses/Address.cs

A missing site address error can occur when creating a site, but exiting before adding a site address to the site management

Missing Site Address

---

prime-angular-frontend/src/app/modules/adjudication/pages/enrollee-review-status/enrollee-review-status.component.html
prime-angular-frontend/src/app/modules/adjudication/pages/enrollee-review-status/enrollee-review-status.component.ts
prime-angular-frontend/src/app/modules/adjudication/shared/components/adjudication-container/adjudication-container.component.ts

* Refresh on adjudication action

Refresh Status

---

prime-angular-frontend/src/app/modules/enrolment/pages/pharmanet-enrolment-summary/pharmanet-enrolment-summary.component.html
prime-angular-frontend/src/app/modules/enrolment/pages/pharmanet-enrolment-summary/pharmanet-enrolment-summary.component.scss
prime-angular-frontend/src/app/modules/enrolment/pages/pharmanet-enrolment-summary/pharmanet-enrolment-summary.component.ts

* Increased feedback to user after copying to clipboard
* Clean up of unused styles

Copy Clipboard

---

prime-angular-frontend/src/app/app-routing.module.ts
prime-angular-frontend/src/app/app.module.ts
prime-angular-frontend/src/app/modules/phsa-eforms/phsa-eforms-routing.module.ts

* Reduce memory foot print of the application

Lazy load PHSA

---

prime-angular-frontend/src/app/modules/enrolment/pages/access-agreement-history-enrolment/access-agreement-history-enrolment.component.html
prime-angular-frontend/src/app/modules/enrolment/pages/access-agreement-history-enrolment/access-agreement-history-enrolment.component.ts
prime-angular-frontend/src/app/modules/enrolment/shared/services/enrolment-resource.service.ts
prime-angular-frontend/src/app/shared/components/enrollee/enrollee-review/enrollee-review.component.html

* Change endpoint URL to current API
* Update template to prevent failing during load
* Added missing verified address fields

Enrollee History Submission

---

prime-angular-frontend/src/app/modules/adjudication/shared/components/adjudicator-notes/adjudicator-notes.component.html

- save button was improperly disabled when typing notes

Bug: Site Registration Note Save Button Disabled

---

prime-angular-frontend/src/app/modules/adjudication/shared/components/enrollee-table/enrollee-table.component.html

- made it consistent with backend which uses 'enrollee_triage'

Bug: Fixed Role for Assign/Reassign Button in Enrolment

---

documentation/Keycloak settings/realm-export-dev.json
documentation/Keycloak settings/realm-export-prod.json
documentation/Keycloak settings/realm-export-test.json

Created new client scope for eForms that does not include date of birth, and removed address scope.

PRIME-1452 - Remove DOB and Address from eForms JWT

---

prime-angular-frontend/src/app/shared/components/forms/site-information-form/site-information-form.component.html

appended tip text for pec field of private community practice site reg

PRIME-1601 Tip for SiteID for non-pharmacy site reg

---

prime-angular-frontend/src/app/modules/adjudication/shared/components/enrollee-table/enrollee-table.component.html

added icon for 'editable' status of enrolment submission

PRIME-1574 Enabling editing of a submission needs persistent status

---

prime-angular-frontend/src/app/modules/adjudication/pages/site-overview/site-overview.component.ts
prime-angular-frontend/src/app/shared/components/paginator/paginator.component.ts

- init siteID on site overview
- scroll to page top after paginating

PRIME-1625 Adjudication Bugs

---

prime-e2e-tests/SiteRegistrationTests.cs
prime-e2e-tests/TestParameters.cs
prime-e2e-tests/TestPrimeE2E.csproj
prime-e2e-tests/run-tests.cmd

Fix so that at least these tests run to completion against `develop` branch/environment:
```
TestPrimeE2E.Enrollment.EnrollmentTests.FullFamilyPhysician_HappyPath
TestPrimeE2E.Enrollment.EnrollmentTests.MedicalOfficeAssistant_HappyPath 
TestPrimeE2E.SiteRegistration
```
Also `run-tests.cmd` makes it easier for people to run the tests.

Augment e2e tests

---

prime-dotnet-webapi/Controllers/PrimeControllerBase.cs

Fix Broken OPTIONS Request

---

README.md

- included alternate way of running app that worked for me

update readme to include alternate way of running app locally

---

prime-dotnet-webapi/Startup.cs

Teeny refactor, just alphabetizing the services in Startup.cs

Alphabetize Services

---

infrastructure/prime-app-ephemeral-template.yml
infrastructure/prime-app-template.yml
prime-angular-frontend/openshift.dockerfile

- use Bitnami NGINX container image
- use combined nginx.conf file

Improve frontend containers

---

infrastructure/prime-app-ephemeral-template.yml
infrastructure/prime-app-template.yml

- delete document manager migration job
- run migration in init-container

Run migrations during pod initialization

---

prime-e2e-tests/Admin.Tests.cs
prime-e2e-tests/BaseTest.cs
prime-e2e-tests/Enrollment.Tests.cs
prime-e2e-tests/SiteRegistrationTests.cs
prime-e2e-tests/run-tests.cmd

See `prime-e2e-tests\README.md`.  
Ran all tests successfully against `dev` (or `develop` code locally) and `pr-1517` (Angular 12) OpenShift environments

Fix so Enrollment and Site Registration tests should be now working

---

prime-angular-frontend/src/app/modules/adjudication/shared/components/search-form/search-form.component.ts
prime-dotnet-webapi/Services/EnrolleeService.cs

Quick and dirty way to get paper enrollee filtering shoehorned into the status filter.

PRIME 1779 filter paper enrollees

---

prime-dotnet-webapi-tests/Unit Tests/SoapService.Tests.cs

Fix Github Check Warning

---

prime-angular-frontend/src/app/modules/gis-enrolment/pages/ldap-information-page/ldap-information-page.component.html
prime-angular-frontend/src/app/modules/gis-enrolment/pages/ldap-information-page/ldap-information-page.component.ts
prime-angular-frontend/src/app/modules/gis-enrolment/shared/models/ldap-error-response.model.ts
prime-angular-frontend/src/app/modules/gis-enrolment/shared/resources/gis-enrolment-resource.service.ts
prime-dotnet-webapi/Controllers/GisController.cs
prime-dotnet-webapi/HttpClients/LDAP Api/LdapClient.cs
prime-dotnet-webapi/Models/Api/GisUserRepresentation.cs
prime-dotnet-webapi/Services/GisService.cs
prime-dotnet-webapi/Startup.cs
prime-dotnet-webapi/ViewModels/GisLdapUser/GisLdapUser.cs

* GIS removed lockoutTimeInHours
* Null check on LDAP response

GIS Updates

---

prime-angular-frontend/src/app/modules/gis-enrolment/pages/ldap-information-page/ldap-information-page.component.html
prime-angular-frontend/src/app/modules/gis-enrolment/shared/resources/gis-enrolment-resource.service.ts

* Email and phone contact info
* Default for unlocked header

GIS Update

---

.github/workflows/build-pr.yml
documentation/Keycloak settings/realm-export-dev.json
documentation/Keycloak settings/realm-export-test.json
infrastructure/prime-app-ephemeral-template.yml
prime-angular-frontend/src/app/modules/adjudication/shared/components/banner-maintenance/banner-maintenance.component.html
prime-angular-frontend/src/app/modules/adjudication/shared/components/notification-email-view/notification-email-view.component.html
prime-angular-frontend/src/app/modules/auth/shared/enum/role.enum.ts
prime-dotnet-webapi/Auth/AuthConstants.cs
prime-dotnet-webapi/Controllers/BannersController.cs
prime-dotnet-webapi/Controllers/EmailsController.cs

Added role prime_maintenance in keycloak, the role can view and edit banners, the role can edit email templates

PRIME-1796 Create a new role for "maintenance"

---

prime-dotnet-webapi/HttpClients/Keycloak Administration/KeycloakApiDefinitions.cs
prime-dotnet-webapi/Services/GisService.cs

NOTE: Update already applied to TEST

GIS update phoneNumber to phone

---

documentation/Keycloak settings/realm-export-test.json

Service Account has been added to Test and Ivan has added client secret to test env.

PRIME-1867 - Add App Service Account in test

---

prime-angular-frontend/src/app/shared/components/site/overview-container/overview-container.component.html

Show business licence in overview for site reg

---

prime-angular-frontend/src/app/modules/enrolment/pages/care-setting/care-setting.component.ts
prime-angular-frontend/src/app/modules/enrolment/pages/obo-sites-page/obo-sites-page.component.html
prime-angular-frontend/src/app/modules/enrolment/pages/obo-sites-page/obo-sites-page.component.ts

Allow the addition of obosites for new health authority care settings on renewal
NOTE: Applied to test already

Fix obosites on renewal

---

prime-dotnet-webapi/Services/SiteService.cs

- set SubmittedDate to null to indicate current status in frontend
**NOTE:** Already applied to TEST

PRIME-1873 No indication of site status to user on site registration card

---

infrastructure/prime-app-ephemeral-template.yml

Fix document manager failures in PRs.

[OPS] increase docman resource limit

---

prime-dotnet-webapi-tests/Utils/Auth/BearerTokenBuilder.cs

Since the fix to this is stuck in the PR for Device Provider enrollment until we can merge it, I've pulled this out to stop the warnings.

Fix Check Warning

---

prime-angular-frontend/src/app/modules/sat-eforms/shared/modules/sat-eforms-login-page/sat-eforms-login-page.component.html
prime-angular-frontend/src/app/modules/sat-eforms/shared/modules/sat-eforms-login-page/sat-eforms-login-page.component.ts
prime-angular-frontend/src/app/shared/components/auth/prime-enrolment-access/prime-enrolment-access.component.html
prime-angular-frontend/src/app/shared/components/auth/prime-enrolment-access/prime-enrolment-access.component.ts
prime-angular-frontend/src/app/shared/components/auth/simple-access/simple-access.component.html
prime-angular-frontend/src/app/shared/components/auth/site-reg-access/site-reg-access.component.html
prime-angular-frontend/src/app/shared/components/auth/site-reg-access/site-reg-access.component.ts
prime-angular-frontend/src/environments/config-map.model.ts
prime-angular-frontend/src/environments/environment.prod.ts

Already applied to TEST for production deployment

PRIME-1985 Additional text for SA eForms Enrolment landing page

---

prime-dotnet-webapi/ViewModels/Parties/GisChangeModel.cs
prime-dotnet-webapi/ViewModels/Parties/GisViewModel.cs

HPDID should not be set in a GIS enrollment.

Remove HPDID From GIS Enrollment

---

prime-angular-frontend/src/app/modules/site-registration/pages/hours-operation-page/hours-operation-page.component.ts

Routing from hours of operation to remote users

PRIME-2003 Fix community site routing

---

prime-angular-frontend/src/app/modules/enrolment/pages/access-declined/access-declined.component.html
prime-angular-frontend/src/app/shared/components/prime-phone/prime-phone.component.ts

[JIRA ticket](https://bcgovmoh.atlassian.net/jira/software/c/projects/PRIME/boards/1?modal=detail&selectedIssue=PRIME-2002)
**Testing steps**
- create an enrolment and then login as admin and decline it
- login to enrolment to see declined message

PRIME-2002 update user facing decline msg

---

prime-angular-frontend/src/app/modules/adjudication/shared/components/adjudication-container/adjudication-container.component.ts
prime-angular-frontend/src/app/modules/adjudication/shared/components/search-form/search-form.component.ts
prime-angular-frontend/src/app/modules/adjudication/shared/services/adjudication-resource.service.ts
prime-angular-frontend/src/app/shared/enums/status-filter.enum.ts
prime-dotnet-webapi/Configuration/Database/Unseeded Tables/BusinessEventConfiguration.cs
prime-dotnet-webapi/Migrations/20211118005718_SoftenBusinessEventOnDelete.Designer.cs
prime-dotnet-webapi/Migrations/20211118005718_SoftenBusinessEventOnDelete.cs
prime-dotnet-webapi/Models/Api/EnrolleeSearchOptions.cs
prime-dotnet-webapi/Models/BusinessEventType.cs
prime-dotnet-webapi/Services/BusinessEventService.cs
prime-dotnet-webapi/Services/EnrolleeService.cs

Improved the filter for paper enrollees, allowing selecting linked / unlinked (claimed/unclaimed).
Also softened Business Event OnDelete behavior to allow deleting of objects but keeping the events.

PRIME-1965 - Filter Paper Enrollees

---

prime-angular-frontend/src/app/modules/site-registration/pages/organization-claim-page/organization-claim-page.component.html

[Jira ticket](https://bcgovmoh.atlassian.net/jira/software/c/projects/PRIME/boards/1?modal=detail&selectedIssue=PRIME-1993)

PRIME-1993 Wording adjustment on site claiming

---

infrastructure/prime-app-template.yml

fix `CACHE_REDIS_HOST` environment variable

[HOTFIX] Fix DocumentManager environment variable

---

prime-dotnet-webapi/Controllers/EnrolleesController.cs

Initial fix for redirect to be refactored and made more generic

Updated redirect to get the enrollee directly

---

prime-angular-frontend/src/app/modules/enrolment/shared/services/enrolment-resource.service.ts
prime-angular-frontend/src/app/shared/components/dialogs/content/triage/triage.component.html
prime-angular-frontend/src/app/shared/components/dialogs/content/triage/triage.component.ts
prime-angular-frontend/src/app/shared/models/enrolment-status-admin.model.ts

https://bcgovmoh.atlassian.net/browse/PRIME-2020

PRIME-2020 Clicking Triage icon causes endless loop of errors

---

prime-angular-frontend/src/app/core/resources/site-resource.service.ts
prime-angular-frontend/src/app/modules/adjudication/pages/site-overview/site-overview.component.ts
prime-dotnet-webapi/Controllers/SitesController.cs
prime-dotnet-webapi/Services/SiteService.cs
prime-dotnet-webapi/Services/interfaces/ISiteService.cs

https://bcgovmoh.atlassian.net/browse/PRIME-2020

PRIME-2019 Pressing Save Site causes a crash an an infinite loop

---

prime-angular-frontend/src/app/modules/enrolment/pages/care-setting/care-setting.component.html
prime-angular-frontend/src/app/modules/enrolment/pages/care-setting/care-setting.component.ts

[PRIME-2025](https://bcgovmoh.atlassian.net/jira/software/c/projects/PRIME/boards/1?modal=detail&selectedIssue=PRIME-2025)
1. Login as a brand new enrollee
2. Enter phone# and email
3. Save and continue
4. do not select any care settings
5. click back (to bcsc-demographics)
6. click Save and Continue
you should go back to Care Settings page without issues
You can try adding multiple care settings without making a selection, or mix and match between selections then repeat steps 6 and 7

PRIME -2025 Error during Enrollment if go Back from Care Setting screen without choosing any care setting

---

utilities/PlrIntakeUtility/PlrIntakeUtility.csproj
utilities/PlrIntakeUtility/PlrIntaker.cs
utilities/PlrIntakeUtility/Program.cs

| Scenario                                                            | Expected                                                                                                                    |
| ------------------------------------------------------------------- | --------------------------------------------------------------------------------------------------------------------------- |
| Something about row is unparseable (e.g.  a date value)             | Saving row fails and log indicates which row by IPC                                                                         |
| Input file has header row and invalid rows                          | Correct number of records, i.e. excluding header row and invalid rows but including all others                              |
| Row …

Fix - Read PLR extract as csv file

---

prime-angular-frontend/src/app/modules/site-registration/shared/components/business-licence-expiry/business-licence-expiry.component.html
prime-angular-frontend/src/app/modules/site-registration/shared/components/business-licence-expiry/business-licence-expiry.component.ts
prime-angular-frontend/src/app/modules/site-registration/shared/services/site-form-state.service.ts
prime-angular-frontend/src/app/shared/components/forms/site-information-form/site-information-form.component.html
prime-angular-frontend/src/app/shared/components/site/overview-container/overview-container.component.html

**Steps to Replicate**
Locally on a separate branch:
1. Create 3 sites:
* 1 x Community Practice
* 2 x Community Pharmacy where one defers their business licence
2. Submit and approve each site
3. Remove the Expiry Date from each Business Licence in the database
4. Attempting to resubmit each site will fail (won't make it to modal)
5. Switch local branch to this branch and attempt to resubmit (will make it to modal)

PRIME-2035 Site Submission Prevent by Missing Expiry Date/Do Business As Validation

---

documentation/Keycloak settings/realm-export-test.json

Device Provider feature flag is added to test for all users.

Update Test Keycloak With Device Provider Feature Flag

---

.codeclimate.yml

disabled checks for similar code, keeping the checks for identical code

Remove noisy code climate comments regarding similar code

---

prime-angular-frontend/src/app/modules/gis-enrolment/pages/submission-confirmation-page/submission-confirmation-page.component.html
prime-angular-frontend/src/app/modules/site-registration/pages/organization-name-page/organization-name-page.component.html
prime-angular-frontend/src/app/shared/components/address-autocomplete/address-autocomplete.component.html
prime-angular-frontend/src/assets/unsupported.html

[Jira ticket](https://bcgovmoh.atlassian.net/jira/software/c/projects/PRIME/boards/1?modal=detail&selectedIssue=PRIME-2048)

PRIME-2048 Safe Cross-Origin Destination Links

---

infrastructure/prime-app-template.yml

migration containers were not receiving latest container images

[ops] Fix migrations

---

prime-angular-frontend/src/app/modules/enrolment/pages/obo-sites-page/obo-sites-page.component.ts
prime-angular-frontend/src/app/modules/enrolment/shared/classes/enrolment-profile-page.class.ts

Steps to test in ticket
https://bcgovmoh.atlassian.net/browse/PRIME-2207

Fix: Obo Form Forced Patch

---

prime-dotnet-webapi/Services/CommunitySiteService.cs

Reproduction steps are listed in https://bcgovmoh.atlassian.net/browse/PRIME-2227
Fix can be tested at https://pr-2166.pharmanetenrolment.gov.bc.ca/site

PRIME-2227 Hours of operation not sorted properly

---

prime-angular-frontend/src/app/modules/enrolment/pages/access-agreement/access-agreement.component.html

https://bcgovmoh.atlassian.net/browse/PRIME-2243
https://pr-2172.pharmanetenrolment.gov.bc.ca/info

PRIME-2243 Remove "you have been approved.." text

---

documentation/Keycloak settings/realm-export-dev.json
documentation/Keycloak settings/realm-export-prod.json
documentation/Keycloak settings/realm-export-test.json
prime-angular-frontend/src/app/modules/adjudication/shared/components/enrollee-table/enrollee-table.component.html
prime-angular-frontend/src/app/modules/adjudication/shared/components/enrollee-table/enrollee-table.component.spec.ts
prime-angular-frontend/src/app/modules/adjudication/shared/components/site-registration-table/site-registration-table.component.html
prime-angular-frontend/src/app/modules/adjudication/shared/components/site-registration-table/site-registration-table.component.spec.ts
prime-dotnet-webapi/Configuration/Auth/AuthConstants.cs
prime-dotnet-webapi/Controllers/EnrolleePaperSubmissionsController.cs
prime-dotnet-webapi/Controllers/EnrolleesController.cs
prime-dotnet-webapi/Controllers/EnrolleesExtendedController.cs
prime-dotnet-webapi/Services/EnrolleeService.cs
prime-dotnet-webapi/Services/interfaces/IEnrolleeService.cs

1. Setup your user profile in Keycloak to only have the "Paper Enrolment Clerk" group.  That is, do not be part of the "Manager" group e.g. 
2. Being only in this group should reduce your Roles to the following:
3. Now log into https://pr-2171.pharmanetenrolment.gov.bc.ca/admin and try to function as a "Paper Enrolment Clerk"

PRIME-2236 Role for paper enrolment

---

prime-dotnet-webapi/Configuration/Database/Seeded Tables/LicenseDetailConfiguration.cs
prime-dotnet-webapi/Migrations/20220728220607_Aug1stEnrolmentLogicChange.Designer.cs
prime-dotnet-webapi/Migrations/20220728220607_Aug1stEnrolmentLogicChange.cs

Update 5 license detail records for Aug 1st enrolment policy change.

PRIME-2257 - Database update

---

prime-angular-frontend/src/app/modules/adjudication/adjudication-routing.module.ts

quick fix - add route to correct component.

PRIME-2244 Fix 404 error

---

prime-dotnet-webapi/Services/Rules/AutomaticAdjudicationRules.cs

- To record the correct prefix when record not found.

PRIME-2276 Update logging for non-prescriber check

---

prime-dotnet-webapi/DTOs/AgreementEngine/AgreementEngineDto.cs
prime-dotnet-webapi/Engines/AgreementEngine Internal/CertificationDigest.cs
prime-dotnet-webapi/Services/Rules/MinorUpdateRules.cs

Implement logic that highlighted in the red rectangle on the flow chart.
https://pr-2199.pharmanetenrolment.gov.bc.ca/info

PRIME-2285 TOA logic update

---

prime-angular-frontend/src/app/shared/components/forms/college-certification-form/college-certification-form.component.html
prime-angular-frontend/src/app/shared/components/forms/college-certification-form/college-certification-form.component.scss
prime-angular-frontend/src/app/shared/components/forms/college-certification-form/college-certification-form.component.ts
prime-dotnet-webapi/Services/EnrolleeService.cs

- Use CSS to capitalize PharmaNet ID
- Use onChange event to convert the input string to uppercase
Note: Please let me know if there is better implementation.
https://pr-2202.pharmanetenrolment.gov.bc.ca/info

PRIME-2292 Upper Case PharmaNet ID

---

prime-angular-frontend/src/app/modules/adjudication/shared/components/adjudication-container/adjudication-container.component.ts
prime-angular-frontend/src/app/shared/enums/enrollee-status-action.enum.ts
prime-dotnet-webapi-tests/Unit Tests/SubmissionStateEngine.Tests.cs
prime-dotnet-webapi/Controllers/SubmissionsController.cs
prime-dotnet-webapi/Engines/EnrolleeStatusStateEngine.cs
prime-dotnet-webapi/Models/Api/EnrolleeStatusAction.cs
prime-dotnet-webapi/Services/SubmissionService.cs

Unlocking profile should bring the enrolment to Under Review Status with no notification.
https://pr-2200.pharmanetenrolment.gov.bc.ca/admin

PRIME-2222 Unlock Profile changes

---

prime-dotnet-webapi/Services/CommunitySiteService.cs

When testing, consider using `moh-prime\utilities\create-mock-data` to create Org and Site data

PRIME-2271 Orgs with multiple sites in admin view are causing confusion

---

prime-dotnet-webapi/Engines/Gpid.cs

- remove "I", "O", "1", "0", "." and "," in the GPID character set

Update GPID character set

---

prime-dotnet-webapi/Models/Enrollee.cs

- change the prefix from "NOBCSC" to "NABCSC"

Update GPID NOBCSC prefix

---

.github/workflows/build-develop.yml

Updating build-develop git action to use docker cmd

Updating build-develop git action to use docker cmd

---

prime-angular-frontend/src/app/modules/site-registration/pages/business-licence-page/business-licence-page.component.html
prime-angular-frontend/src/app/modules/site-registration/pages/business-licence-page/business-licence-page.component.ts
prime-angular-frontend/src/app/shared/components/site/overview-container/overview-container.component.html

https://pr-2288.pharmanetenrolment.gov.bc.ca/site

PRIME-2409 Update Site Business Licence page static text

---

prime-angular-frontend/src/app/modules/auth/shared/services/auth.service.ts

- refactor a bit on the way the code pull values from token
- update getAdmin side to match getUser

PRIME-2458 Error Popup on Provisioner Link page

---

prime-angular-frontend/src/app/modules/enrolment/pages/obo-sites-page/obo-sites-page.component.html
prime-angular-frontend/src/app/modules/enrolment/pages/obo-sites-page/obo-sites-page.component.ts

PRIME-2389 Obo Job Site changes

---

prime-dotnet-webapi/Services/Rules/AutomaticAdjudicationRules.cs

This reverts commit 8ddd19836a3439ec558346e7d7c5e980f1afb80c.

Revert "PRIME-2400 Update Practitioner Verification logic (#2284)"

---

prime-angular-frontend/src/app/shared/components/forms/site-information-form/site-information-form.component.html

Feedback from Leanne during "Support Business Testing of items listed in PRIME-2514" meeting

PRIME-2462 - Clarify Site Name instruction

---

prime-dotnet-webapi/Controllers/JobsController.cs
prime-dotnet-webapi/Services/ReportingService.cs

- add parameters to API endpoint
- add logging within the service method

fix - Update reporting back end process

---

prime-angular-frontend/src/app/modules/health-auth-site-reg/shared/modules/health-auth-site-reg-login-page/health-auth-site-reg-login-page.component.ts

Enable button
regardless of environment

PRIME-2347 Enable for Authorized Users

---

prime-angular-frontend/src/app/shared/components/dialogs/content/change-vendor-note/change-vendor-note.component.html
prime-angular-frontend/src/app/shared/components/dialogs/content/change-vendor-note/change-vendor-note.component.spec.ts
prime-angular-frontend/src/app/shared/components/dialogs/content/change-vendor-note/change-vendor-note.component.ts

PRIME-2583 - Requested text changes

---

prime-angular-frontend/src/app/modules/site-registration/pages/site-management-page/site-management-page.component.html
prime-angular-frontend/src/app/modules/site-registration/pages/site-management-page/site-management-page.component.ts

https://pr-2400.pharmanetenrolment.gov.bc.ca/site

PRIME-2592 UI Update - Multiple Organization Support

---

prime-dotnet-webapi/Configuration/Auth/AuthenticationSetup.cs

Control log level by setting LogLevel environment variable to a number corresponding to a Serilog.Events.LogEventLevel number.
e.g. $env:LogLevel = '1' for PowerShell
or set Environment in OpenShift DeploymentConfig:

PRIME-2737 Log roles as well 

---

infrastructure/redis/Dockerfile

For reference: 
- https://developer.gov.bc.ca/docs/default/component/platform-developer-docs/docs/platform-automation/defunct-pids/
- https://dragondscv.medium.com/set-up-init-process-in-kubernetes-c2651aded719

PRIME-2787 Add tini init to Redis pods to cleanup zombie processes

---

prime-angular-frontend/src/app/modules/site-registration/pages/care-setting-page/care-setting-page.component.html
prime-angular-frontend/src/app/modules/site-registration/pages/care-setting-page/care-setting-page.component.scss
prime-angular-frontend/src/app/modules/site-registration/pages/care-setting-page/care-setting-page.component.ts
prime-angular-frontend/src/app/shared/components/auth/prime-enrolment-access/prime-enrolment-access.component.html
prime-angular-frontend/src/app/shared/components/auth/prime-enrolment-access/prime-enrolment-access.component.scss

Waiting for the content to be finalized!

PRIME-2803 reflect changes at CareConnect

---

prime-angular-frontend/src/app/modules/site-registration/pages/care-setting-page/care-setting-page.component.html
prime-angular-frontend/src/app/modules/site-registration/pages/care-setting-page/care-setting-page.component.scss
prime-angular-frontend/src/app/modules/site-registration/pages/care-setting-page/care-setting-page.component.ts
prime-angular-frontend/src/app/shared/components/auth/prime-enrolment-access/prime-enrolment-access.component.html
prime-angular-frontend/src/app/shared/components/auth/prime-enrolment-access/prime-enrolment-access.component.scss

This reverts commit 7f69811cd975e8033c5f43570672e0730527bc95.

Revert "PRIME-2803 reflect changes at CareConnect (#2614)"

---

infrastructure/prime-app-template.yml

Should fix "Multi-Attach Error"

change the strategy type for document-manager

---

prime-dotnet-webapi/Configuration/Environment/PrimeEnvironmentVariablesConfigurationProvider.cs
prime-dotnet-webapi/Configuration/PrimeConfigurationObjects.cs
prime-dotnet-webapi/Controllers/EmailsController.cs
prime-dotnet-webapi/HttpClients/Mail/ChesClient.cs
prime-dotnet-webapi/HttpClients/Mail/IChesClient.cs
prime-dotnet-webapi/Services/EmailService.cs
prime-dotnet-webapi/Services/interfaces/IEmailService.cs
prime-dotnet-webapi/appsettings.json

Added CHES_RETRY_WITHIN_HOURS to `ches` ConfigMap.
Switched CHES_ENABLED to `true` in `dev` environment.  Set `dev-send-renewal-emails` cron job to be suspended

PRIME-2867 Use "promote" API to address CHES unreliability

---

.github/workflows/build-demo.yml
.github/workflows/build-develop.yml
.github/workflows/build-main.yml
.github/workflows/build-pr.yml
.github/workflows/build-test.yml
.github/workflows/build-tools.yml
.github/workflows/pr-cleanup.yml

See https://github.com/actions/runner-images/issues/11101

The Ubuntu 20.04 Actions runner image will be fully unsupported by 2025-04-01

---

prime-angular-frontend/src/app/modules/adjudication/shared/components/banner-maintenance/banner-maintenance.component.html
prime-angular-frontend/src/app/modules/enrolment/pages/absence-management-page/absence-management-page.component.html
prime-angular-frontend/src/app/modules/enrolment/pages/remote-access-addresses/remote-access-addresses.component.html
prime-angular-frontend/src/app/modules/health-auth-site-reg/pages/authorized-user-page/authorized-user-page.component.html
prime-angular-frontend/src/app/modules/health-auth-site-reg/pages/site-information-page/site-information-page.component.html
prime-angular-frontend/src/app/modules/site-registration/pages/organization-name-page/organization-name-page.component.html
prime-angular-frontend/src/app/modules/site-registration/pages/organization-signing-authority-page/organization-signing-authority-page.component.html
prime-angular-frontend/src/app/modules/site-registration/pages/remote-user-page/remote-user-page.component.html
prime-angular-frontend/src/app/shared/components/dialogs/content/change-vendor-note/change-vendor-note.component.html
prime-angular-frontend/src/app/shared/components/dialogs/content/claim-note/claim-note.component.html
prime-angular-frontend/src/app/shared/components/forms/address-form/address-form.component.html
prime-angular-frontend/src/app/shared/components/forms/college-certification-form/college-certification-form.component.html
prime-angular-frontend/src/app/shared/components/forms/college-certification-form/college-certification-form.component.ts
prime-angular-frontend/src/app/shared/components/forms/contact-information-form/contact-information-form.component.html
prime-angular-frontend/src/app/shared/components/forms/email-form/email-form.component.html
prime-angular-frontend/src/app/shared/components/forms/fields/doing-business-as-form-field/doing-business-as-form-field.component.html
prime-angular-frontend/src/app/shared/components/forms/preferred-name-form/preferred-name-form.component.html
prime-angular-frontend/src/app/shared/components/forms/unlisted-college-licence-form/unlisted-college-licence-form.component.html
prime-angular-frontend/src/app/shared/components/obo-site-form/obo-site-form.component.html
prime-angular-frontend/src/app/shared/components/site/contact-profile-form/contact-profile-form.component.html

All issues in Jira item are addressed, including #8

PRIME-2908 Address new `placeholder` behavior

---

.github/workflows/build-demo.yml
.github/workflows/build-test.yml

Due to increased requests for cpu and memory (#2705), need to lower number of replicas

Two replicas for `demo` and `test`

---

prime-dotnet-webapi/Services/CommunitySiteService.cs
prime-dotnet-webapi/Services/EmailDocumentsService.cs
prime-dotnet-webapi/Services/SiteService.cs
prime-dotnet-webapi/ViewModels/SiteRegistration/SiteRegistrationReviewViewModel.cs
prime-dotnet-webapi/Views/SiteRegistrationReview.cshtml

- fix sorting in Admin page
- add remote user created date and sorting in site submission document

OHID-344 Remote User Issue - missing changes

---

prime-angular-frontend/src/app/modules/site-registration/pages/remote-user-page/remote-user-page.component.html
prime-angular-frontend/src/app/modules/site-registration/pages/remote-user-page/remote-user-page.component.ts

Remote user college license information can't be duplicated within a site

OHID-344 Remote User Issue - update validation

---

prime-dotnet-webapi/Configuration/Database/Seeded Tables/LicenseDetailConfiguration.cs
prime-dotnet-webapi/Migrations/20250707172429_FNHAChangeUpdate.Designer.cs
prime-dotnet-webapi/Migrations/20250707172429_FNHAChangeUpdate.cs

- fix effective date of the license detail record update

OHID-346 FNHA Special Site - fix effective date

---

prime-angular-frontend/src/app/shared/components/auth/prime-enrolment-access/prime-enrolment-access.component.scss

Can not see HA passcode as font color is white.

OHID-354 Fix Passcode Colour
