prime-angular-frontend/package.json, prime-angular-frontend/sonar-project.properties
To run this - just call 'npm run sonar' and it will run the 'ng test' and create code coverage files, and then run the sonar scanner to push to sonar.  Config which sonar instance to send to in the sonar-project.properties file.  It also includes puppeteer which allows the tests to run headless.
=> adding scripts to run code coverage and push to sonar

documentation/Keycloak settings/realm-export-dev.json, documentation/Keycloak settings/realm-export-test.json
settings JSON files have been updated to reflect new state of keycloak. 
Token now has birthdate and address from BCSC.
Unrelated, BCeID has been added to the project since the last time the settings have been updated.
=> Added Address and Birthdate to Keycloak

prime-dotnet-webapi-tests/Controllers/EnrolleesController.Tests.cs, prime-dotnet-webapi-tests/Mocks/BaseMockService.cs, prime-dotnet-webapi-tests/Mocks/EnrolleeServiceMock.cs, prime-dotnet-webapi-tests/Services/DefaultEnrolleeService.Tests.cs, prime-dotnet-webapi-tests/Utils/TestUtils.cs, prime-dotnet-webapi/Controllers/EnrolleesController.cs, prime-dotnet-webapi/Extensions/ClaimsPrincipalExensions.cs, prime-dotnet-webapi/Services/DefaultEnrolleeService.cs, prime-dotnet-webapi/Services/IEnrolleeService.cs
Refactorings:
- Removed random generation of enrollee Ids from enrollee service mock. Replaced with new utility method on base service mock class. Removed unnecessary constants.
- Removed a lot of unnecessary casts and unused variables from tests. Minor syntactic changes for readability.
- BelongsToEnrollee is now an extension method on ClaimsPrincipal rather than in the enrollee controller. Renamed to CanAccess.
- Added EnrolleeUserIdExistsAsync method to the enrollee service. Interface and mock have been updated. Renamed EnrolleeExists to EnrolleeExistsAsync.
- Moved CanAccess up in the execution sequence for some controller methods, generally right after checking if the enrollee object is null. Check auth as soon as possible. 
- Capitallized setAllPharmaNetStatusesFalseAsync.
- …
=> Refactoring and cleanup of enrollee controller + service

prime-angular-frontend/src/app/modules/adjudication/pages/enrolment/enrolment.component.spec.ts, prime-angular-frontend/src/app/modules/enrolment/pages/job/job.component.ts, prime-angular-frontend/src/app/modules/enrolment/pages/overview/overview.component.html, prime-angular-frontend/src/app/modules/enrolment/pages/overview/overview.component.scss, prime-angular-frontend/src/app/modules/enrolment/pages/overview/overview.component.spec.ts, prime-angular-frontend/src/app/modules/enrolment/pages/overview/overview.component.ts, prime-angular-frontend/src/app/modules/enrolment/shared/services/enrolment-state.service.ts, prime-angular-frontend/src/app/shared/components/enrollee/enrollee-property-error/enrollee-property-error.component.html, prime-angular-frontend/src/app/shared/components/enrollee/enrollee-property-error/enrollee-property-error.component.scss, prime-angular-frontend/src/app/shared/components/enrollee/enrollee-property-error/enrollee-property-error.component.spec.ts, prime-angular-frontend/src/app/shared/components/enrollee/enrollee-property-error/enrollee-property-error.component.ts, prime-angular-frontend/src/app/shared/components/enrollee/enrollee-review/enrollee-review.component.html, prime-angular-frontend/src/app/shared/shared.module.ts
added prelim validation on summary such that a user is required to either have a college cert or a job title.
This works through the enrollee state service. As it now have a check for if a cert or job exists.
This then will display a red warning at the top of the summary page as well as an icon next to the job title field. It will also disable the submit button. 
Also for the job form page disabled allow the default "None" so you are required to select a job title once you get to this screen either through the wizard or by spoking to it
=> Validation on Summary

prime-dotnet-webapi/Services/PharmanetAPIService.cs
Pharmanet mock API for local dev is updated based on licence numbers now being alphanumeric and any length.
Parses entire licence number rather than taking the last two digits. Returns the record matching that test card number, but only in the range of 1 to 11. Any other number or parse error is null. Enter "error" for licence number and the mock will throw an error.
=> Update local dev PharmaNet college api mock

prime-angular-frontend/Dockerfile
This didn't break the API but was useful in waking it up.  The API should work fine without it but this will get rid of the annoying 'Waiting for host..."
=> Adding missing port

openshift/dotnet-webapi.dc.yaml
.NET is taking a while to respond 200 on healthcheck endpoint.  This adds more tolerance.
=> changing to 30 second checks, fail on 10 second returns.

prime-dotnet-webapi-tests/Services/MinorUpdateRules.Tests.cs, prime-dotnet-webapi/Services/Rules/MinorUpdateRules.cs
Enrollee could not remove mailing address due to custom comparitor throwing when second argument was null.
Comparitor also now checks by ignoring un-important fields rather than testing important ones to help ensure forwards-compatibility if new fields are added to models.
=> PRIME-639 - Fix pre-rule

documentation/Insert CareConnect Test Data SQL.txt
SQL to insert the test data for CareConnect.  Connect to the database and run this directly.
=> Add SQL for CareConnect test data

prime-dotnet-webapi/Models/SiteRegistration/Organization.cs
Need the navigation property on Organization, it confuses Entity Framework without it (future migrations try to remove the foreign key).
=> Add Missing OrgType Navigation Property

documentation/Keycloak settings/realm-export-dev.json, prime-dotnet-webapi/AuthConstants.cs, prime-dotnet-webapi/AuthenticationSetup.cs, prime-dotnet-webapi/Configuration/StatusReasonConfiguration.cs, prime-dotnet-webapi/Controllers/SubmissionsController.cs, prime-dotnet-webapi/Extensions/ClaimsPrincipalExtensions.cs, prime-dotnet-webapi/Infrastructure/PrimeUserAuthHandler.cs, prime-dotnet-webapi/Migrations/20200528235623_NonBcscStatusReason.Designer.cs, prime-dotnet-webapi/Migrations/20200528235623_NonBcscStatusReason.cs, prime-dotnet-webapi/Models/Enrollee.cs, prime-dotnet-webapi/Models/Statuses/StatusReasonType.cs, prime-dotnet-webapi/Services/Rules/AutomaticAdjudicationRules.cs, prime-dotnet-webapi/Services/SubmissionRulesService.cs, prime-dotnet-webapi/ViewModels/Enrollee/EnrolleeProfileViewModel.cs
BCeID has now been enabled in Dev only. BCeID requires two-factor authentication using GoogleAuth or FreeOTP (only FreeOTP ahs been tested). Currently, BCeIDs are automatically granted the prime_user role and have access to the application normally. A new auto-adjudication rule will flag any identity providers that are not BC Services Card to manual review (in addition to flagging any IDPs that have an assurance level of 2 or lower).
At this point, the assurance level requirement has been removed from our API's Auth policies, due to BCeID having an assurance level of 1.
=> PRIME-259 - BCeID

prime-dotnet-webapi/Models/EnrolmentCertificate.cs, prime-dotnet-webapi/Services/EnrolmentCertificateService.cs
The Enrollment Certificate link for provisioners failed due to the schema of the profile history changing, making it unable to find the organization types.
The decision was made to take the easy fix and let the organization types be "out of sync" with the application. When an enrollee re-submits their application, any change to organization types will be displayed immediately on the provisioner link while the application is under veview/awaiting TOA acceptance.
=> PRIME-902 - Enrolment Certificate Bug

Jenkinsfile.promotion
Document Manager was missing deploy commands in `Jenkinsfile.promotion`. So while it was able to be built, it did not deploy to test and prod.
=> HOTFIX: Get Document Manager to actually deploy for real to Test and Prod

openshift/document-manager.dc.yaml
The Document Manager API, outside of PR branches, does not have its PVC claim binded to the pod volume. This means that with every deploy, we are wiping all storage. Additionally, we are not seeing equal replication between pods as a potential consequence of this behaviour.
This is being rectified by binding the PVC claim created for this service by binding it to the respective pod's volume.
=> FIX: Ensuring PVC claim is binded to pod volume

prime-angular-frontend/src/app/shared/components/document-upload/document-upload/document-upload.component.ts
The frontend will now send file uploads in chunks of 1MB. This does not limit the size of the file upload, only the size of the data sent at once.
This could  be parameterized or made into an environment variable in the future, it's a hard-coded value for now.
=> 1 MB File Upload Chunk Size

prime-dotnet-webapi/Models/BaseDocumentUpload.cs
Document GUD is JSON ignored in the backend, this prevents document downloads from working.
=> Un-Ignore Document GUID

docker-compose.yml, document-manager/backend/Dockerfile, document-manager/backend/app.sh, document-manager/backend/openshift.dockerfile, document-manager/backend/requirements.txt, openshift/document-manager-ephemeral.dc.yaml, openshift/document-manager.dc.yaml, openshift/postgresql.dc.yaml, openshift/postgresql.ephemeral.dc.yaml
Force Document Manager migrate pod to wait for PostgreSQL to finish deploying, avoiding a race condition where the migrate pod will attempt to run before PostgreSQL becomes available.
=> FIX: Force Document Manager Migrate to wait for PostgreSQL deployment completion

Jenkinsfile.production, Jenkinsfile.test
* `Jenkinsfile.release` has been renamed to `Jenkinsfile.production` to better reflect its purpose: building and deploying the master branch to **Production**.
* A new hotfix stage has been added to `Jenkinsfile.production` - this is intended to simplify any hotfixes that are required for our master branch.
* Hotfixes will be deployed to the `test` OpenShift environment. They will exist there as temporary environments, and are to be removed upon the closing of the respective PR. 
* Hotfix PRs will be accessible using the following URL format: `https://PR-<PR #>.pharmanetenrolment.gov.bc.ca`
=> FEATURE: Provide Production with Hotfix stage

prime-angular-frontend/src/app/modules/enrolment/pages/pharmanet-enrolment-summary/pharmanet-enrolment-summary.component.ts, prime-angular-frontend/src/app/shared/models/enrolment.model.ts, prime-angular-frontend/src/test/mocks/mock-enrolment.service.ts, prime-dotnet-webapi-tests/ModelFactories/EnrolleeFactory.cs, prime-dotnet-webapi/Models/Enrollee.cs, prime-dotnet-webapi/Services/EnrolleeService.cs, prime-dotnet-webapi/Services/PrivilegeService.cs
Privileges on Enrollees is not used or displayed currently and requires extra database hits to populate.
This PR is to remove the Privileges property in a single PR so it can be reverted later if need be.
=> Remove Privileges

prime-dotnet-webapi-tests/Extensions/EnrolleeExtensions.cs, prime-dotnet-webapi-tests/Unit Tests/MinorUpdateRules.Tests.cs, prime-dotnet-webapi/Services/Rules/MinorUpdateRules.cs, prime-dotnet-webapi/Services/SubmissionService.cs, prime-dotnet-webapi/ViewModels/Enrollee/EnrolleeUpdateModel.cs
Minor update rule now correctly behaves again. However, we cannot currently tell if new self declaration documents are uploaded to an existing self declaration due to the documents being uploaded outside of the submission of a new profile. See https://bcgovmoh.atlassian.net/browse/PRIME-1023.
=> PRIME-907 - Fix Minor Update Rule

prime-angular-frontend/src/app/shared/components/document-upload/document-upload/document-upload.component.ts
First (smaller) part of ticket 851 adds the allowed file types to the idle label of Filepond. Should handle any list of allowed file types, and does not have any extra text if no allowed filetypes are supplied (in case we allow all file types in the future somewhere).
=> PRIME-1025 - File Upload Label Includes Allowed File Types

prime-dotnet-webapi/Services/SubmissionRulesService.cs
Having remote users no longer triggers manual adjudication.
=> PRIME-1097 - Remove Remote User Rule

openshift/angular-frontend.dc.yaml, prime-angular-frontend/nginx.template.conf, prime-angular-frontend/nginxdev.conf, prime-angular-frontend/nginxprod.conf, prime-angular-frontend/nginxtest.conf
Adding a PHSA eForms URL so that immunizers don't use the main PharmaNet Enrolment URL.
=> Add temporary PHSA eForms URL

prime-angular-frontend/src/app/config/config.model.ts, prime-angular-frontend/src/app/modules/enrolment/pages/regulatory/regulatory-form-state.ts, prime-angular-frontend/src/app/modules/enrolment/shared/models/college-certification.model.ts, prime-angular-frontend/src/app/shared/components/college-certification-form/college-certification-form.component.html, prime-angular-frontend/src/app/shared/components/college-certification-form/college-certification-form.component.ts, prime-angular-frontend/src/app/shared/components/enrollee/enrollee-review/enrollee-review.component.html, prime-dotnet-webapi/Controllers/LookupsController.cs, prime-dotnet-webapi/HttpClients/College Licence API/CollegeLicenceClient.cs, prime-dotnet-webapi/Migrations/20210126064650_AddedCertificationPractitionerId.Designer.cs, prime-dotnet-webapi/Migrations/20210126064650_AddedCertificationPractitionerId.cs, prime-dotnet-webapi/Models/Certifications/Certification.cs, prime-dotnet-webapi/Models/Certifications/License.cs
Testing using Postman:
1. Login as an Admin and get the access_token and add this to Auth Bearer Token
2. POST to the Lookups endpoint /validate-licence with collegePrefix 91 and practitionerId 20111 as query params
`https://pr-1081.pharmanetenrolment.gov.bc.ca/api/v1/Lookups/validate-licence?collegePrefix=91&practitionerId=20111`
=> PRIME-1356 CLONE - College Licence Information and Practitioner ID

prime-dotnet-webapi/entrypoint.sh
Shouldn't attempt a migration when there's no DB connection
=> Exit when no DB connection

prime-angular-frontend/src/app/modules/enrolment/shared/services/enrolment-form-state.service.ts
Remote access fields (physicalAddress and siteVendors) were not being patched outside of the remote access page since they weren't in the form state and were showing up as dashes in overview since the fields were always null.
=> Remote access fields not being patched

schemaspy/Dockerfile
=> Updated caddy download url in schemaspy

prime-angular-frontend/src/app/modules/adjudication/shared/components/adjudication-container/adjudication-container.component.ts
Fix for bug when approving an enrolment by blocking the screen until prerequisite request is completed
Bug could not be replicated locally, but appears to be the most likely issue if her network connection is sooo super uber slow that she can open the dropdown, select approve, have the modal open, and either enter/skip adding a note before submitting.
=> Added busy to block until request is finished

documentation/Keycloak settings/realm-export-dev.json, documentation/Keycloak settings/realm-export-test.json
Now that we have deployed to test, removed old roles from keycloak.
=> PRIME-1429 - Remove Old Roles From Test Keycloak

documentation/Keycloak settings/realm-export-prod.json
Old roles are now gone from Keycloak in all environments
=> PRIME-1430 - Remove old roles from Keycloak

prime-dotnet-webapi/Auth/AuthenticationSetup.cs
The MOH Keycloak integration was preventing login due to it unexpectedly still running even after the PRIME Keycloak had already validated the token. This was compounded by the fact that the MOH Keycloak is behind a firewall, so would return 403 FORBIDDEN when the app tried to validate the token.
MOH Keycloak has been removed from the default policy. To use it, you can specify it in the Authorize attribute on a method/controller:
```C#
[Authorize(AuthenticationSchemes = Schemes.MohJwt)]
```
Note that, due to the PRIME scheme being part of the default policy, this example will _also_ run the PRIME JWT Scheme. If this becomes a problem, we may need to set up some explicit policies.
=> Remove MOH Keycloak from default Policy

prime-angular-frontend/src/app/modules/enrolment/pages/regulatory/regulatory.component.ts, prime-angular-frontend/src/app/shared/components/forms/college-certification-form/college-certification-form.component.html, prime-angular-frontend/src/app/shared/components/forms/college-certification-form/college-certification-form.component.ts
Fixes issue where prescriber ID is not available when editing after submission of an enrolment.  Steps to reproduce provided, and should now result in seeing the prescriber ID for appropriate licence codes.
**Reproduction Steps**
* Create an enrolment for a Practicing Nurse Practitioner
* Add a licence number and prescriber ID to the college certification
* Submit the enrolment and accept the TOA
* Attempt to edit the college certificate by routing from the overview
* Prescriber ID won’t be editable
=> PRIME-1531 Prescriber ID Not Editable After Submission

prime-e2e-tests/SiteRegistrationTests.cs, prime-e2e-tests/TestPrimeE2E.csproj
- more robust wait for page to load complete
- increased timeout
- must call driver.quit() on teardown to avoid memory leak
- improved and reliable logic on workflow check
- removed  calls to obsolete code (added reference to SeleniumExtras.WaitHelpers
=> Fix Site registration selenium test

openshift/angular-frontend.dc.yaml
Fixes `The Route "angular-frontend-develop-mutualauth" is invalid: spec.host: Invalid value: "mutualauth-develop.pharmanetenrolment.gov.bc.ca": field is immutable`
FYI, for PLR integration testing, removed route will be re-added in the relevant PR (#1272 currently)
=> Temporary fix for `The Route ... is invalid` error

prime-angular-frontend/src/app/modules/adjudication/pages/enrollee-toa-maintenance-list-page/enrollee-toa-maintenance-list-page.component.ts, prime-angular-frontend/src/app/modules/adjudication/pages/enrollee-toa-maintenance-page/enrollee-toa-maintenance-page.component.html, prime-angular-frontend/src/app/shared/models/agreement-version.model.ts, prime-dotnet-webapi/ViewModels/Agreements/AgreementVersionListViewModel.cs, prime-dotnet-webapi/ViewModels/Agreements/AgreementVersionViewModel.cs, prime-dotnet-webapi/ViewModels/AutoMapping.cs
The "Last Modified Date" on the TOA maintenance page shows September 19th, 2019 for every TOA. This is because it comes from the "Updated Date" column, which is set to Sept 19th for every version. A far more useful date for the current state of the app is the "Effective Date", which is the date that the Agreement Version became effective in the application.
Becomes
We can revisit what data should be displayed on the cards when/if adjudicators have the ability to edit agreements.
=> Use Effective Date instead of Updated Date in TOA Maintenance page

prime-dotnet-webapi/Controllers/AdminsController.cs, prime-dotnet-webapi/Controllers/AuthorizedUsersController.cs, prime-dotnet-webapi/Controllers/DocumentAccessController.cs, prime-dotnet-webapi/Controllers/DocumentManagerController.cs, prime-dotnet-webapi/Controllers/EnrolleeAgreementsController.cs, prime-dotnet-webapi/Controllers/EnrolleePaperSubmissionsController.cs, prime-dotnet-webapi/Controllers/EnrolleesController.cs, prime-dotnet-webapi/Controllers/HealthAuthoritiesController.cs, prime-dotnet-webapi/Controllers/OrganizationsController.cs, prime-dotnet-webapi/Controllers/ProvisionerAccessController.cs, prime-dotnet-webapi/Controllers/SitesController.cs, prime-dotnet-webapi/Controllers/SubmissionsController.cs
There are three options for the `ActionResult` returned from our controller methods:
```C#
ActionResult
ActionResult<Result>
IActionResult
```
In the beginning of our app, we typed all of our `ActionResult`s because that's what we thought we had to do. Turns out, typing `ActionResult` does not work the way one might intuitively assume. It does **not** specify that the method will return an object of that type.  What is does is allow you to return *either* an `ActionResult`, *or* an object of the specified type. So theoretically with `ActionResult<Enrollee>` we could do
```C#
return(enrollee);
```
rather than
```C#
return Ok(enrollee);
```
But this is not actually whats happening: our API responses are all wrapped in an `ApiResultResponse` object, so for this to be accurate it would have …
=> Unify ActionResult

prime-angular-frontend/src/app/core/modules/keycloak/keycloak-init.service.ts, prime-angular-frontend/src/app/core/services/console-logger.service.ts, prime-angular-frontend/src/app/modules/auth/shared/guards/authentication.guard.ts, prime-angular-frontend/src/app/shared/components/document-upload/document-upload/document-upload.component.ts, prime-angular-frontend/src/environments/config-map.model.ts, prime-angular-frontend/src/environments/environment.model.ts, prime-angular-frontend/src/main.ts
With the recent update to allow swapping of environment variables through OCP4 config maps we should not be access environment files directly, and should only use config injection token for access to these values.  
Will create another update that essentially removes import access of the environment file, but this interim update will fix the issues that will occur outside of our local environments.
=> Remove direct use of environment for config

prime-angular-frontend/src/app/modules/enrolment/pages/overview/overview.component.html
Fix - Feedback from demo
- Hide the green alert "You have approval to access PharmaNet"  when we are within the 90 day period of renewal, we only need to display the blue alert notifying the user of the renewal.
=> Fix - Hide green alert when within the 90 days of renewal

infrastructure/prime-app-ephemeral-template.yml
This should allow us to run more PR deployments simultaniously.
|   | _CPU_  | ______  |  _MEMORY_ |  ______ |
|---|---|---|---|---|
|   | **limit**  |  **request** | **limit**  |  **request** |
|  **frontend**  | 50m  |  15m | 50Mi  |  10Mi |
|  **webapi**  | 50m  |  15m | 1Gi  |  500Mi |
|  **docman**  | 25m  |  10m | 128Mi  |  28Mi |
|  **redis**  | 25m  |  5m | 100Mi  |  50Mi |
|  **postgres**  | 50m  |  10m | 512Mi  |  100Mi |
=> [OPS] Add resource limits to PR deployments

prime-angular-frontend/src/app/shared/components/site/overview-container/overview-container.component.html
Hides 2 redirect icons in site reg overview admin and [PRIME-1826 Site Registration Allow Editing of All Pages](https://github.com/bcgov/moh-prime/pull/1616) handles addresses
=> PRIME-1860 site reg - edit icons appear in admin screens

infrastructure/prime-app-template.yml
Reference to secret for redis password was incorrectly set to `app-db-password`. this PR fixes it.
=> [hotfix] correct secret key

infrastructure/prime-app-ephemeral-template.yml, infrastructure/prime-app-template.yml
- let imagechange trigger in deployment config automatically update correct image tag for init containers
fixes initcontainers not running latest migrations
=> [hotfix] use correct image tag

prime-dotnet-webapi/README.md
After a few instances of confusion around setting local backend secrets I've updated the documentation slightly
=> Update Local Secrets Documentation

prime-angular-frontend/src/app/shared/components/site/overview-container/overview-container.component.html
Create a community site and submit, update the expiry date in the database to push the site into renewal, and the business licence button will be displayed, but after submission when InReview it will not be displayed.
=> PRIME-2001 inappropriate appearance of Update Business License button

prime-angular-frontend/src/app/shared/components/forms/site-information-form/site-information-form.component.html
Toggling the switch to on for Community Sites that have chosen PCHP or Device Provider should hide the checkbox.
=> PRIME-2000 hide "this site is already operational..." check in PCHP Site Reg if "new site without SiteID" slider is on

prime-dotnet-webapi/ViewModels/Enrollee/RemoteAccessSiteViewModel.cs
Updating/submitting an `Enrollee` with Remote Site(s) fails due to the view model not having `SiteId` any more, so the de-serialized object has `SiteId = 0` which fails the foreign key constraint
Repro:
1. Create a Community Practice Site with known Remote User Certification
2. Approve Site
2. Create Enrollee With matching Certification, and add the Site as a Remote Site
3. (Optional) Submit Enrollee and Enable editing
4. Navigate to the Demographics page and hit "Save and Continue"
Update fails with a foreign key violation on RemoteAccessSite table.
=> PRIME-2036 - Fix Enrollee Remote Access Update Bug

.github/dependabot.yml
Update the dependabot file to stop suggesting major version updates for NuGet files, and stop SoapCore updates since newer versions are a breaking change.
=> Update Dependabot for NuGet

prime-angular-frontend/src/app/modules/enrolment/shared/services/enrolment-form-state.service.ts
In the enrollee workflow 
- select care setting Health Authority
- select no certs
- add obo site info
- proceed to overview and try to submit
without fix validation fails
=> Fix When Selecting HA for enrollee overview validation for OBO site

prime-angular-frontend/src/app/lib/classes/abstract-enrolment-page.class.ts, prime-angular-frontend/src/app/modules/site-registration/pages/remote-user-page/remote-user-page.component.ts, prime-angular-frontend/src/app/modules/site-registration/pages/remote-users-page/remote-users-page.component.html, prime-angular-frontend/src/app/modules/site-registration/pages/remote-users-page/remote-users-page.component.ts
To test navigate every which way from the remote users to remote user page, and try and do actions on a dirty form and cancel.
Only one state that it doesn't handle perfectly is if a user 
- on a fresh page toggles to add remote user
- adds a remote user
- removes said user
- hits the back button
they are then prompted about unsaved changes
=> fix remote user navigation and form state management

prime-angular-frontend/src/app/modules/gis-enrolment/shared/modules/gis-login/gis-login-page.component.ts
At `/gis`, on clicking "Logon with Health Authority ID", should see PHSA login page rather than IDIR login page
=> PRIME-2091 Switch IdentityProvider for GIS 

prime-dotnet-webapi/HttpClients/Keycloak Administration/KeycloakApiDefinitions.cs
Needed for GIS users, now that we are using the PHSA login. These users have no attributes, so are returning no attribute key on the user representation.
=> Fix Keycloak Client for Users with no Attributes

prime-dotnet-webapi/Configuration/Database/Seeded Tables/IdentifierTypeConfiguration.cs, prime-dotnet-webapi/Migrations/20220208205331_UpdateIdentifierTypeNdid.Designer.cs, prime-dotnet-webapi/Migrations/20220208205331_UpdateIdentifierTypeNdid.cs
The result of this implementation is that distribution messages for naturopath providers should create a record with `PlrProvider.IdentifierType` equal to "NDID" rather than "NAPID".  To test:
This step is *not* necessary if using PLR to send the distribution message. 
Open an existing test message (e.g. `moh-prime\prime-dotnet-webapi-tests\Integration\PRPM_IN301030CA.xml`) and modify the //healthCareProvider/id node that contains the college id (that is, not CPN, IPC, or MSPID) …
… to a naturopathic doctor identifier.  For a more realistic message, //healthCareProvider/code/@code can also be updated.  For example, after changes:
1. `setx PLR_INTEGRATION_CLIENT_CERT_THUMBPRINT 6FA357305008C8EA814EA98768C21783DCCA374E`
2. Start web-api in a way that ensures the …
=> PRIME-2132 Update PRIME copy of PLR Identifier Types

prime-dotnet-webapi-tests/Unit Tests/AgreementEngine.Tests.cs
Used a generator to clean up test data for the Agreement Engine test rather than inline data.
Also, increased test cases from 42 to 108
=> Simplify Agreement Engine Test Data

prime-angular-frontend/src/app/modules/adjudication/shared/components/site-registration-container/site-registration-container.component.html
Looks like over the course of admin changes the handler for enable editing in site reg fell off, this adds it back in
=> Fix: Enable Editing site reg handling

prime-angular-frontend/src/app/modules/enrolment/pages/overview/overview.component.ts
Did some testing of test with the couple cherry picked changes and looks like it still allowed to submit with this error
And alternative was a little more work to go through and add validation as James mentioned. I may put in a ticket to clean this all up but time was the major factor in this case.
=> Fix: Stop submission with missing prescriber id

infrastructure/prime-app-ephemeral-template.yml, infrastructure/prime-app-template.yml
Update Kubernetes health checks for webapi.
- add param to end of api/healthcheck
- set liveness probe’s failureThreshold to 3
=> [ops] improve startup, readiness, and liveness probes for webapi

prime-dotnet-webapi/Services/SubmissionService.cs
Testing:
1. Go to admin before change and re-run rules on an enrollee. It will fail.
2. Do it after deploying the change, it will pass.
Only affects re-running the rules since in the submission service we lucked out since the enrollee it previously interacted with from the DB and cached so when we grab it again even though it doesn't have the includes it still has the careSettings attached.
=> Fix: re-run rules missing include

infrastructure/prime-app-ephemeral-template.yml, infrastructure/prime-app-template.yml, prime-dotnet-webapi/Controllers/HealthcheckController.cs
Mapping multiple routes to the same healthcheck to allow the existing logging to tell which type of healthcheck was called.
=> Make Healthchecks more Self-Documenting

prime-angular-frontend/src/app/shared/components/auth/prime-enrolment-access/prime-enrolment-access.component.html
The alert shouldn’t be placed between `.row` and `.col`.  A `.row` ’s only child should be a `.col` where the `.col` contains the content for the grid
=> Fix login cancelled alert layout

prime-angular-frontend/src/app/modules/site-registration/pages/overview-page/overview-page.component.ts
In the site registration workflow, navigate from the site management page to the organization overview page. You should now get there and not have a looping error that crashes your browser.
=> PRIME-2226 Organization overview display error

prime-dotnet-webapi/Controllers/ProvisionerAccessController.cs
Update API to return "Bad request" when number of hpdid exceeds the limit
- GetUpdatedGpid - limited to 1000 Hpdids
- HpdidLookup - limited to 10 Hpdids
Note: Please the postman testing collection v1.1 in Teams under PRIME Developer
=> PRIME-2312 Update API with limit error

prime-dotnet-webapi/openshift.dockerfile
Looks like postgress removed "stretch" repo. We are using mcr.microsoft.com/dotnet/aspnet:5.0 which is based on Debian "buster".
=> Updating postgress source repo

prime-angular-frontend/src/app/modules/enrolment/pages/access-agreement-current/access-agreement-current.component.html, prime-angular-frontend/src/app/modules/enrolment/pages/access-agreement-current/access-agreement-current.component.ts, prime-angular-frontend/src/app/modules/enrolment/shared/services/enrolment-resource.service.ts, prime-angular-frontend/src/app/shared/models/agreement.model.ts, prime-dotnet-webapi/Controllers/EnrolleeAgreementsController.cs, prime-dotnet-webapi/Controllers/OrganizationsController.cs, prime-dotnet-webapi/Services/AgreementService.cs, prime-dotnet-webapi/Services/EnrolleeAgreementService.cs, prime-dotnet-webapi/Services/OrganizationService.cs, prime-dotnet-webapi/Services/Razor/RazorTemplates.cs, prime-dotnet-webapi/Services/SubmissionService.cs, prime-dotnet-webapi/Services/interfaces/IAgreementService.cs, prime-dotnet-webapi/Services/interfaces/IOrganizationService.cs, prime-dotnet-webapi/Views/Agreements/AgreementPdfNoSignature.cshtml
Note:
- Organization Agreement PDF will be created and stored in Document Manager. Then it will be treated as uploaded agreement PDF that a record will be created in SignedAgreementDocument table as a reference. 
- Similar to Organization Agreement, TOA PDF will be created and stored in Document Manager, and a record will be created in SignedAgreementDocument table. 
- Default filename of the organization agreement is "Organization-Agreement.pdf", which matches the name in the existing frontend code.
- Default filename of the TOA is "Terms-of-Access.pdf", which matches the name in the existing frontend code.
- TOA PDF can be downloaded from Terms-of-Access page logged as Enrollee. However, it can't be downloaded by Admin at this point.
https://pr-2222.pharmanetenrolment.gov.bc.ca/info
=> Feature/PRIME-2306 Store Org. Agreement and ToA in document manager

prime-dotnet-webapi-tests/testsettings.json, prime-dotnet-webapi/Configuration/Environment/PrimeEnvironmentVariablesConfigurationProvider.cs, prime-dotnet-webapi/HttpClients/Mail/ChesClient.cs, prime-dotnet-webapi/appsettings.json
Best to test in PR environment:  https://pr-2249.pharmanetenrolment.gov.bc.ca/
Set `CHES_ENABLED` to true, and delete the `webapi` pod so that a new one reads the ConfigMap update:
Note that this can then send to legitimate email addresses, e.g.
For DevOps purposes, a new secret key is needed in each PRIME OC project (e.g. test, prod)
=> PRIME-2361 Adapt to CHES API changes

prime-angular-frontend/src/app/modules/health-auth-site-reg/pages/health-auth-care-type-page/health-auth-care-type-form-state.class.ts, prime-angular-frontend/src/app/modules/health-auth-site-reg/pages/health-auth-care-type-page/health-auth-care-type-page.component.html, prime-angular-frontend/src/app/modules/health-auth-site-reg/pages/health-auth-care-type-page/health-auth-care-type-page.component.ts, prime-angular-frontend/src/app/modules/health-auth-site-reg/shared/models/health-authority-care-type.model.ts, prime-angular-frontend/src/app/modules/health-auth-site-reg/shared/models/health-authority-vendor.model.ts, prime-angular-frontend/src/test/mocks/mock-health-authority-site.service.ts, prime-dotnet-webapi/ApiDbContext.cs, prime-dotnet-webapi/Migrations/20230215025133_SeparateHACareTypeToVendorRelationship.Designer.cs, prime-dotnet-webapi/Migrations/20230215025133_SeparateHACareTypeToVendorRelationship.cs, prime-dotnet-webapi/Models/Health Authorities/HealthAuthorityCareTypeToVendor.cs, prime-dotnet-webapi/Services/HealthAuthorityService.cs, prime-dotnet-webapi/ViewModels/Health Authorities/HealthAuthorityCareTypeViewModel.cs, prime-dotnet-webapi/ViewModels/Health Authorities/HealthAuthorityViewModel.cs
Review this PR rather than https://github.com/bcgov/moh-prime/pull/2261
To test, the new table `HealthAuthorityCareTypeToVendor` needs to be populated.  For example, given 
and 
`HealthAuthorityCareTypeToVendor` could be setup like this:
Registering a Health Authority Site should filter Vendor choices based on the Care Type selected.  Editing a Health Authority through the Admin screens should be unaffected and continue to work properly.
=> PRIME-2332 Health Authority Site Registration - Vendor selection limited by care type

prime-dotnet-webapi/Controllers/EmailsController.cs, prime-dotnet-webapi/HttpClients/Mail/ChesClient.cs, prime-dotnet-webapi/Services/EmailService.cs
To assist with testing, see 
This PR:
- prevents invalid email addresses, as detected by `MailAddress`, from being attempted to send out
- handles errors from `SmtpEmailClient` which can occur if email address passes `MailAddress` validation but fails CHES validation
Additionally the PR: 
- provides more information in API call response
- should avoid creating "CHES Exception: Sequence contains no elements" ERR message in logs
To use CHES in the PR environment, set the following
=> PRIME-2457 Handle invalid email address during SendEnrolleeRenewalEmails

prime-dotnet-webapi/Services/SubmissionService.cs
- not calling the Production PharmaNet API (but instead, mocked API) caused `NotInPharmanet` to be the status reason
- this fix addresses skewed data
- using `AsSplitQuery` in this context and other References should not be a problem (verified results are identical before and after using `AsSplitQuery`)
=> PRIME-2594 Implement fix and address performance

prime-dotnet-webapi/Configuration/Auth/AuthenticationSetup.cs
Control log level by setting LogLevel environment variable to a number corresponding to a Serilog.Events.LogEventLevel number.
e.g. `$env:LogLevel = '1'` for PowerShell
=> PRIME-2737 Log token used to call `GetGpidDetail`

prime-angular-frontend/package.json, prime-angular-frontend/yarn.lock
Bump ip from 1.1.5 to 1.1.9 in /prime-angular-frontend 
Bump follow-redirects from 1.14.1 to 1.15.6 in /prime-angular-frontend 
Bump tinymce from 5.10.9 to 7.0.0 in /prime-angular-fronten 
Bump express from 4.17.1 to 4.19.2 in /prime-angular-frontend 
Bump tar from 6.1.11 to 6.2.1 in /prime-angular-frontend 
Bump axios from 1.3.4 to 1.7.4 in /prime-angular-frontend 
Bump http-proxy-middleware from 2.0.6 to 2.0.7 in /prime-angular-frontend 
Bump cross-spawn from 7.0.3 to 7.0.6 in /prime-angular-frontend
=> Combine Frontend Libraries Update

prime-angular-frontend/src/app/lib/models/remote-user.model.ts, prime-angular-frontend/src/app/modules/site-registration/pages/remote-user-page/remote-user-page.component.html, prime-angular-frontend/src/app/modules/site-registration/pages/remote-user-page/remote-user-page.component.ts, prime-angular-frontend/src/app/shared/components/site/remote-user-review/remote-user-review.component.html, prime-angular-frontend/src/test/mocks/mock-community-site.service.ts, prime-dotnet-webapi/Models/SiteRegistration/RemoteUser.cs, prime-dotnet-webapi/Services/CommunitySiteService.cs, prime-dotnet-webapi/Services/SiteService.cs
- add validation to avoid duplicate remote user entry in PCHP
- update API to skip duplicate remote user entry
- update the business logic that finds matching remote user from enrolment to use notified flag instead of site approved date. so that when signing authority tries to add more remote user and bring the site o review status, the enrollee is still able to add remote access.
- add the remote user created date in admin page and sort the remote user by created date in descending order
=> OHID-344 Remote User Issues
